ALTER TABLE careprovider
  ADD COLUMN IF NOT EXISTS serviceType VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS consultationFee DECIMAL(10,2) NULL,
  ADD COLUMN IF NOT EXISTS experienceYears INT NULL,
  ADD COLUMN IF NOT EXISTS licenseNumber VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS providerAddress VARCHAR(255) NULL;
