ALTER TABLE servicerequest
  ADD COLUMN IF NOT EXISTS visitLatitude DECIMAL(10,7) NULL,
  ADD COLUMN IF NOT EXISTS visitLongitude DECIMAL(10,7) NULL,
  ADD COLUMN IF NOT EXISTS visitAddress VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS locationNote VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS symptoms TEXT NULL,
  ADD COLUMN IF NOT EXISTS isUrgent TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS additionalNotes TEXT NULL,
  ADD COLUMN IF NOT EXISTS paymentMethod VARCHAR(50) NULL,
  ADD COLUMN IF NOT EXISTS paymentStatus VARCHAR(30) NULL;
