ALTER TABLE message
  ADD COLUMN messageType VARCHAR(32) NOT NULL DEFAULT 'text',
  ADD COLUMN attachmentUrl TEXT NULL,
  ADD COLUMN attachmentName VARCHAR(255) NULL,
  ADD COLUMN attachmentSize BIGINT NULL,
  ADD COLUMN attachmentMimeType VARCHAR(128) NULL,
  ADD COLUMN medicalRecordId VARCHAR(64) NULL,
  ADD COLUMN voiceDurationSeconds INT NULL,
  ADD COLUMN sentAt DATETIME NULL,
  ADD COLUMN deliveredAt DATETIME NULL,
  ADD COLUMN readAt DATETIME NULL,
  ADD COLUMN isRead TINYINT(1) NOT NULL DEFAULT 0;

UPDATE message SET sentAt = COALESCE(sentAt, createdAt);

CREATE TABLE IF NOT EXISTS chat_presence (
  userId VARCHAR(64) NOT NULL,
  lastActive DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (userId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
