import 'package:flutter/widgets.dart';

import 'package:carelink/core/locale_controller.dart';

class CarelinkL10n {
  const CarelinkL10n(this.locale);

  final Locale locale;

  bool get isArabic => locale.languageCode == 'ar';

  /// Uses [localeController] so toggling AR/EN updates every [tr]/[l10n] call
  /// reliably (does not rely on inherited [Localizations] edge cases).
  static CarelinkL10n of(BuildContext _) {
    return CarelinkL10n(localeController.locale);
  }

  String t(String key, {Map<String, String>? args}) {
    var value = (isArabic ? _ar : _en)[key] ?? _en[key] ?? key;
    if (args != null) {
      for (final entry in args.entries) {
        value = value.replaceAll('{${entry.key}}', entry.value);
      }
    }
    return value;
  }
}

extension CarelinkL10nX on BuildContext {
  CarelinkL10n get l10n => CarelinkL10n.of(this);

  String tr(String key, {Map<String, String>? args}) {
    return l10n.t(key, args: args);
  }
}

const Map<String, String> _en = {
  'app.name': 'CareLink',
  'language.switchToArabic': 'Arabic',
  'language.switchToEnglish': 'English',
  'theme.light': 'Light mode',
  'theme.dark': 'Dark mode',
  'intro.trustPill': 'Trusted. Secure. Smart Care.',
  'intro.headline1': 'Better care,',
  'intro.headline2': 'connected.',
  'intro.subtitle':
      'Get instant AI-powered health insights, book trusted providers, and manage your care journey anywhere.',
  'intro.getStarted': 'Get Started',
  'intro.aiInsights': 'AI Insights',
  'intro.aiInsightsSubtitle': 'Smart health recommendations',
  'intro.findProviders': 'Find Providers',
  'intro.findProvidersSubtitle': 'Book trusted doctors',
  'intro.medications': 'Medications',
  'intro.medicationsSubtitle': 'Manage and order your medicines',
  'intro.healthRecords': 'Health Records',
  'intro.healthRecordsSubtitle': 'Store and access your records',
  'intro.labTests': 'Lab & Tests',
  'intro.labTestsSubtitle': 'Book tests and get reports',
  'intro.consultOnline': 'Consult Online',
  'intro.consultOnlineSubtitle': 'Talk to doctors from anywhere',
  'intro.securePrivate': 'Secure & Private',
  'intro.securePrivateSubtitle': 'Your data is 100% safe',
  'intro.aiPowered': 'AI Powered',
  'intro.aiPoweredSubtitle': 'Smarter health insights',
  'intro.anywhereAccess': 'Anywhere Access',
  'intro.anywhereAccessSubtitle': 'Care at your fingertips',
  'auth.signIn': 'Sign In',
  'auth.loginSubtitle':
      'Access your account to manage your health and appointments.',
  'auth.email': 'Email Address',
  'auth.password': 'Password',
  'auth.rememberMe': 'Remember me',
  'auth.forgotPassword': 'Forgot password?',
  'auth.forgotPasswordTitle': 'Forgot Password',
  'auth.forgotPasswordBody':
      'Enter your email address and we will send you password reset instructions.',
  'auth.cancel': 'Cancel',
  'auth.send': 'Send',
  'auth.orContinueWith': 'or continue with',
  'auth.noAccount': "Don't have an account? ",
  'auth.signUp': 'Sign Up',
  'auth.loginSuccessful': 'Login successful',
  'auth.invalidServerUser': 'Invalid server response: user data not found',
  'auth.enterEmailPassword': 'Please enter email and password',
  'auth.enterValidEmail': 'Please enter a valid email address',
  'auth.enterEmail': 'Please enter your email',
  'auth.resetSent': 'If this email exists, reset instructions have been sent.',
  'auth.doctorNotConnected': 'Doctor dashboard is not connected yet',
  'auth.adminNotConnected': 'Admin dashboard is not connected yet',
  'auth.unknownRole': 'Unknown user role: {role}',
  'auth.microsoftNotConnected':
      'Microsoft sign-in is not connected yet. Use email or Google / Apple.',
  'auth.comingSoon': 'Coming soon',
  'auth.passwordRequired': 'Please enter your password',
  'auth.checkForm': 'Please correct the highlighted fields.',
  'auth.emailNotRegistered': 'Email not registered',
  'auth.checkEmail': 'Check your email for reset instructions.',
  'auth.chooseResetMethod': 'How would you like to reset your password?',
  'auth.resetViaEmail': 'Email',
  'auth.resetViaPhone': 'Phone',
  'auth.phone': 'Phone number',
  'auth.enterPhone': 'Enter your phone number',
  'auth.invalidPhone': 'Enter 8–15 digits only',
  'auth.otpCode': 'Verification code',
  'auth.sendCode': 'Send code',
  'auth.resendIn': 'Resend in {seconds}s',
  'auth.resendCode': 'Resend code',
  'auth.verifyAndContinue': 'Verify code',
  'auth.invalidOtp': 'Invalid or expired code',
  'auth.newPassword': 'New password',
  'auth.confirmNewPassword': 'Confirm new password',
  'auth.resetPassword': 'Update password',
  'auth.phoneNotRegistered': 'Phone not registered',
  'auth.passwordsNoMatch': 'Passwords do not match',
  'auth.verifying': 'Verifying…',
  'auth.devOtpHint': 'Dev OTP: {code}',
  'auth.verificationCodeSentEmail':
      'Verification code sent to your email',
  'auth.verificationCodeSentPhone':
      'Verification code sent to your phone',
  'auth.invalidVerificationCode': 'Invalid verification code',
  'auth.emailVerifiedSuccess': 'Email verified successfully',
  'auth.phoneVerifiedSuccess': 'Phone verified successfully',
  'auth.enterCodeHint':
      'Enter the 6-digit code we sent. Codes expire in 5 minutes.',
  'auth.forgotPasswordEmailSubtitle':
      'We will send a code to your email to confirm you own this address.',
  'auth.forgotPasswordPhoneSubtitle':
      'We will send a code by SMS (when configured) to confirm you own this number.',
  'auth.verifyEmailFirst': 'Verify your email with the code sent before signing up.',
  'auth.verifyPhoneFirst': 'Verify your phone with the code sent before signing up.',
  'patient.allProviders': 'All Providers',
  'patient.voiceUnavailable': 'Voice input is not available on this device.',
  'patient.typeCareNeed': 'Type or say what care you need, then tap Find.',
  'patient.providersLoading':
      'Provider list is still loading - try again shortly.',
  'patient.goodMorning': 'Good morning',
  'patient.goodAfternoon': 'Good afternoon',
  'patient.goodEvening': 'Good evening',
  'patient.recommendedForYou': 'Recommended for you',
  'patient.typeOrSpeak':
      'Type or speak your need. For personalized medical fit, add your record under Profile > Medical Records.',
  'patient.recommended': 'Recommended: {provider}',
  'patient.find': 'Find',
  'patient.stopVoice': 'Stop voice input',
  'patient.speakNeed': 'Speak your care need',
  'patient.signInEditProfile': 'Sign in to edit your profile.',
  'patient.hiLoading': 'Hi...',
  'patient.hiName': 'Hi, {name}',
  'patient.bookNextVisit': 'Book your next visit',
  'patient.homeNursingCare': 'Home Nursing Care',
  'patient.trustedCare': 'Trusted care',
  'patient.book': 'Book',
  'patient.badgeRecommended': 'Recommended',
  'patient.hiFallback': 'there',
  'patient.homeWelcomeSubline': '{greeting}, {welcome}',
  'patient.homeLocationPrefix': 'Location',
  'patient.homeLocationResolving': 'Finding your location…',
  'patient.homeLocationUnavailable':
      'Enable location or add your address in profile.',
  'patient.careProviderGeneric': 'Care provider',
  'patient.providersEmptyFilters': 'No providers match your filters.',
  'patient.providersLoadFailed': 'Unable to load providers. Please try again.',
  'patient.distanceAwayKm': '{km} km away',
  'patient.navHome': 'Home',
  'patient.navCare': 'My care',
  'patient.navChat': 'Chat',
  'patient.navProfile': 'Profile',
  'patient.listening': 'Listening',
  'patient.listeningRequest': 'Listening to your request',
  'patient.askAi': 'Ask CareLink AI',
  'patient.sayOrType': 'Say or type the care you need to rank providers.',
  'nurse.title': 'Care Link - Nurse',
  'nurse.dashboard': 'Dashboard',
  'nurse.requests': 'Requests',
  'nurse.reports': 'Reports',
  'nurse.payments': 'Payments',
  'nurse.settings': 'Settings',
  'nurse.welcome': 'Welcome, {name}',
  'nurse.matter': 'Your healthcare services matter',
  'nurse.quickOverview': 'Quick Overview',
  'nurse.pendingRequests': 'Pending Requests',
  'nurse.todaysVisits': "Today's Visits",
  'nurse.completed': 'Completed',
  'nurse.earnings': 'Earnings',
  'nurse.quickActions': 'Quick Actions',
  'nurse.profile': 'Profile',
  'nurse.profileSubtitle': 'Update your professional profile',
  'nurse.serviceRequests': 'Service Requests',
  'nurse.serviceRequestsSubtitle': 'Accept or reject new requests',
  'nurse.submitReport': 'Submit Report',
  'nurse.submitReportSubtitle': 'Document completed visits',
  'nurse.paymentHistory': 'Payment History',
  'nurse.paymentHistorySubtitle': 'View earnings and payments',
  'nurse.settingsSubtitle': 'Manage profile and preferences',

  'payment.line.unpaidPay':
      'Payment: Visa — Pay with Visa to complete. No cash.',
  'payment.line.unpaidNext':
      'Payment: Visa — Pay with Visa on the next step. No cash.',
  'payment.line.paid': 'Payment: Paid by Visa',
  'payment.line.paidLast4': 'Payment: Paid by Visa • **** {last4}',
  'payment.payWithVisa': 'Pay with Visa',
  'payment.completeTitle': 'Complete payment',
  'payment.completeSubtitleDemo':
      'Demo: approved Visa test cards only — no real charges.',
  'payment.visaCheckout': 'Visa checkout',
  'payment.visaOnlyNote':
      'Visa only. Card details on the next step — full PAN/CVV never stored.',
  'payment.openingCheckout': 'Opening checkout…',
  'payment.successPaid': 'Payment successful',
  'payment.successRecorded': 'Payment recorded',
  'payment.demoNoCharge': 'Demo checkout — no real charge.',
  'payment.pendingCheckout': 'Visa checkout is still pending. Complete payment to confirm.',
  'payment.savedBooking': 'Your booking details were saved.',
  'payment.summary.appointment': 'Appointment',
  'payment.summary.amount': 'Amount',
  'payment.backHome': 'Back to home',
  'payment.amountPositive': 'Amount must be greater than zero.',
  'payment.notCompleted': 'Payment was not completed.',
  'payment.genericError': 'Something went wrong.',
  'payment.demoLedgerNote':
      'Visa demo — test cards only. Full card number and CVV are never stored.',

  'securePayment.title': 'Secure Visa checkout',
  'securePayment.b1':
      'Encrypted traffic between your device and CareLink.',
  'securePayment.b2':
      'Full card numbers, CVV, and expiry are never stored — only safe metadata such as Visa and last four digits.',
  'securePayment.b3':
      'Demo mode uses approved Visa test PANs only; no payment processor keys ship in the app.',
  'securePayment.b4':
      'Visa only — cash and other methods are not accepted.',

  'patient.title.profile': 'Profile',
  'patient.title.reviewBooking': 'Review booking',
  'patient.title.visitReport': 'Visit report',
  'patient.title.appointment': 'Appointment',
  'patient.title.payment': 'Payment',
  'patient.title.bookingDetails': 'Booking details',
  'patient.title.healthRecord': 'Health record',
  'patient.title.paymentHistory': 'Payment history',
  'patient.title.findProviders': 'Find Providers',
  'patient.title.schedule': 'My Schedule',
  'patient.title.myCare': 'My care',
  'patient.careHub.introTitle': 'Appointments & health file',
  'patient.careHub.introBody':
      'Plan visits, maintain your medical file, and use Visit reports for a long-term timeline (symptoms & notes per visit).',
  'patient.careHub.scheduleTitle': 'Appointment schedule',
  'patient.careHub.scheduleSubtitle': 'Filter by status, open each booking',
  'patient.careHub.recordsTitle': 'Medical records',
  'patient.careHub.recordsSubtitle': 'Electronic file, add or edit entries',
  'patient.careHub.linkVisitReports': 'Visit reports (long-term)',
  'patient.careHub.linkSimpleList': 'Upcoming & history (simple list)',
  'patient.careHub.documentedTitle': 'Documented visits',
  'patient.careHub.documentedSubtitle':
      'Completed and cancelled visits stay listed for your records.',
  'patient.careHub.emptyVisits':
      'No past visits yet. When visits are completed or cancelled, they appear here.',

  'patient.appointments.header': 'Appointments',
  'patient.tab.upcoming': 'Upcoming',
  'patient.tab.history': 'History',
  'patient.noAppointments': 'No appointments available.',
  'patient.dateUnavailable': 'Date unavailable',
  'patient.timeUnavailable': 'Time unavailable',
  'patient.providerFallback': 'Provider',
  'patient.role.doctor': 'Doctor',
  'patient.role.nurse': 'Nurse',
  'patient.rateVisitHint': 'Tap to rate this visit',
  'patient.status.pending': 'Pending',
  'patient.status.confirmed': 'Confirmed',
  'patient.status.completed': 'Completed',
  'patient.status.cancelled': 'Cancelled',

  'patient.messages.header': 'Messages',
  'patient.searchMessagesHint': 'Search messages…',
  'patient.noMessagesFound': 'No messages found',

  'patient.profile.noName': 'No name',
  'patient.profile.noEmail': 'No email',
  'patient.profile.accountType': 'Account type',
  'patient.profile.deleteNote':
      'Disable/Delete account will be added in a secure flow soon.',
  'patient.menu.editProfile': 'Edit Profile',
  'patient.menu.medicalRecords': 'Medical Records',
  'patient.menu.paymentHistoryMenu': 'Payment history',
  'patient.menu.notifications': 'Notifications',
  'patient.menu.logout': 'Logout',
  'patient.field.email': 'Email',
  'patient.field.phone': 'Phone',
  'patient.field.address': 'Address',
  'patient.field.dob': 'Date of Birth',
  'patient.field.gender': 'Gender',
  'patient.healthTab.records': 'Records',
  'patient.healthTab.profile': 'Profile',
  'patient.healthTab.timeline': 'Timeline',
  'patient.healthBaseline.title': 'Baseline medical profile',
  'patient.healthBaseline.body':
      'Keep chronic conditions, allergies, and medications up to date. '
      'These support safer care and better recommendations. '
      'Official diagnoses after visits appear in the Records tab.',
  'patient.healthBaseline.editCta': 'Edit profile & health baseline',
  'patient.profileCard.ageDob': 'Age / DOB',
  'patient.profileCard.chronicConditions': 'Chronic conditions',
  'patient.profileCard.allergies': 'Allergies',
  'patient.profileCard.medications': 'Current medications',

  'patient.welcomeBack': 'welcome back!',
  'patient.upcomingAppointment': 'Upcoming Appointment',
  'patient.viewDetailsGt': 'View details >',
  'patient.browsePopularProviders': 'Browse popular providers below',
  'patient.consultation': 'Consultation',
  'patient.favorites': 'Favorites',
  'patient.seeAllGt': 'See all >',
  'patient.providerSpecialty': 'Provider Specialty',
  'patient.popularProviders': 'Popular Providers',
  'patient.smartMatchExplainerFull':
      'Smart match uses your current case, medical file, specialty, distance, availability, ratings & experience.',
  'patient.smartMatchExplainerAddRecord':
      'Add a medical record or describe your care need for stronger matches.',
  'patient.aiCareMatch': 'AI care match',
  'patient.aiMedicalFileHint':
      'Your saved medical file is included in the score (conditions & allergies vs provider role/specialty), plus distance, availability, ratings & experience.',
  'patient.aiSmartMatchFallback': 'AI smart match',
  'patient.careSearchHint':
      'e.g. diabetes follow-up, pediatrician, cardiology, available now',
  'patient.notificationsTooltip': 'Notifications',
  'patient.sortSmart': 'Smart match',
  'patient.sortTopRated': 'Top Rated',
  'patient.sortAz': 'A-Z',
  'patient.filterAll': 'All',
  'patient.filterAvailableNow': 'Available Now',
  'patient.reschedule': 'Reschedule',
  'patient.joinNow': 'Join Now',
  'patient.paymentHistory.empty': 'No payments yet.',

  'patient.action.tryAgain': 'Try again',
  'patient.action.apply': 'Apply',
  'patient.action.reset': 'Reset',
  'patient.action.continue': 'Continue',
  'patient.action.saveChanges': 'Save changes',
  'patient.providers.searchHint': 'Search doctor, nurse, or specialty',
  'patient.providers.loadFailedShort': 'Failed to load providers.',
  'patient.providers.noMatchFilters':
      'No providers match your search or filters.',
  'patient.providers.minRating': 'Min rating: {value}',
  'patient.location.useCurrent': 'Use current location',
  'patient.location.placeHint':
      'Type a city or place name, then choose a result',
  'patient.location.confirm': 'Confirm location',
  'patient.location.pickVisitSubtitle':
      'Choose where the provider will visit you',
  'patient.selectService.title': 'What type of service do you need?',
  'patient.selectService.subtitle':
      'Choose the service that best fits your needs.',
  'patient.service.homeNursing.title': 'Home nursing',
  'patient.service.homeNursing.desc':
      'Skilled care at home with nursing support.',
  'patient.service.wound.title': 'Wound care',
  'patient.service.wound.desc': 'Dressing and professional wound management.',
  'patient.service.injection.title': 'Injection',
  'patient.service.injection.desc':
      'Medication administration by a qualified nurse.',
  'patient.service.elderly.title': 'Elderly care',
  'patient.service.elderly.desc':
      'Respectful support for daily comfort and health.',
  'patient.service.docConsult.title': 'Doctor consultation',
  'patient.service.docConsult.desc': 'Virtual or in-person physician visit.',
  'patient.service.followup.title': 'Follow-up visit',
  'patient.service.followup.desc': 'Continuity of care and progress check.',
  'patient.request.reasonVisit': 'Reason for visit',
  'patient.request.symptomsOptional': 'Symptoms (optional)',
  'patient.request.notesOptional': 'Additional notes (optional)',
  'patient.booking.pickDateTime':
      'Please choose a date and time first.',
  'patient.booking.chooseDateTimeSubtitle':
      'Choose your preferred date and time.',
  'patient.booking.timesShownLocal':
      'Available times are shown in your local timezone.',
  'patient.request.currentCase': 'Current case',
  'patient.request.currentCaseBody':
      'This applies only to this booking. Your provider uses it to prepare, and recommendations can match more accurately.',
  'patient.request.reasonPlaceholder':
      'Describe the reason for your visit',
  'patient.request.symptomsPlaceholder':
      'Describe any symptoms you are having',
  'patient.request.additionalPlaceholder':
      'Any other information you want to share',
  'patient.request.urgentTitle': 'Is this urgent?',
  'patient.request.urgentSub':
      'We will prioritize your request when possible.',
  'patient.request.detailsHeaderTitle': 'Case details',
  'patient.request.detailsSubtitle': 'Tell us what you need for this visit',
  'patient.request.infoStripDetailed':
      'Detailed information helps your provider prepare for the visit.',
  'patient.request.confidentialLine':
      'Your information is kept confidential.',
  'patient.chat.hintMessage': 'Type a message…',
  'patient.visitReport.submit': 'Submit report',
  'patient.visitReport.needDiagnosis': 'Add diagnosis or treatment plan.',
  'patient.visitReport.vitalsInvalidJson':
      'Vital signs must be valid JSON.',
  'patient.visitReport.visitDate': 'Visit date',
  'patient.visitReport.medsPrescribed': 'Medications prescribed (optional)',
  'patient.visitReport.allergiesNotedVisit':
      'Allergies noted this visit (optional)',
  'patient.visitReport.vitalsJsonLabel': 'Vital signs (JSON)',
  'patient.visitReport.diagnosis': 'Diagnosis',
  'patient.visitReport.treatmentPlan': 'Treatment plan',
  'patient.visitReport.recommendations': 'Recommendations',
  'patient.visitReport.followUpDate': 'Follow-up date',
  'patient.record.block.vitals': 'Vital signs',
  'patient.record.block.diagnosis': 'Diagnosis',
  'patient.record.block.treatmentPlan': 'Treatment plan',
  'patient.record.block.recommendations': 'Recommendations',
  'patient.record.block.meds': 'Medications',
  'patient.record.block.allergiesVisit': 'Allergies (visit)',
  'patient.record.block.notes': 'Notes',
  'patient.record.block.followUp': 'Follow-up',
  'patient.booking.cancelSuccess': 'Appointment cancelled successfully.',
  'patient.booking.cancelCta': 'Cancel booking',
  'patient.booking.cancelReasonApp': 'Cancelled from mobile app',
  'patient.pay.amountUnavailable':
      'Amount unavailable. Complete payment from the booking checkout flow.',
  'patient.pay.careVisit': 'Care visit',
  'patient.pay.amountAtCheckout': 'Amount set at checkout ({currency})',
  'patient.pay.statusLine': 'Status: {status}',
  'patient.booking.banner.acceptTitle':
      'Accepted — visit on your schedule',
  'patient.booking.banner.acceptSub':
      'Follow the provider on the map when they share live location.',
  'patient.booking.banner.pendingTitle': 'Awaiting provider response',
  'patient.booking.banner.pendingSub':
      'The provider may accept or decline. We notify you here.',
  'patient.booking.banner.completedTitle': 'Visit completed',
  'patient.booking.banner.completedSub':
      'Rate your provider after the visit — it helps future matches.',
  'patient.detail.provider': 'Provider',
  'patient.detail.role': 'Role',
  'patient.detail.specialization': 'Specialization',
  'patient.detail.dateTime': 'Date & time',
  'patient.detail.status': 'Status',
  'patient.detail.notes': 'Notes',
  'patient.detail.location': 'Location',
  'patient.detail.visitAddress': 'Visit address',
  'patient.detail.locationNote': 'Location note',
  'patient.detail.symptoms': 'Symptoms',
  'patient.detail.urgency': 'Urgency',
  'patient.detail.urgencyUrgent': 'Urgent',
  'patient.detail.urgencyNormal': 'Normal',
  'patient.visitRating.title': 'Your rating',
  'patient.visitRating.ratePrompt': 'Rate this visit',
  'patient.visitRating.scaleExplain':
      '1 = poor, 5 = excellent. This updates provider scores for smart match.',
  'patient.visitRating.optionalComment': 'Optional comment',
  'patient.visitRating.pickStars': 'Please choose a star rating from 1 to 5.',
  'patient.visitRating.submitBtn': 'Submit rating',
  'patient.visitRating.thanks':
      'Thanks! Your rating helps improve recommendations.',
  'patient.schedule.ratingSavedThanks':
      'Thank you — your rating was saved.',
  'patient.schedule.rateProvider': 'Rate provider',
  'patient.schedule.scheduledDate': 'Scheduled date',
  'patient.schedule.scheduledTime': 'Scheduled time',
  'patient.schedule.paymentPrefix': 'Payment: {detail}',
  'patient.schedule.cancelledBadge': 'Cancelled',
  'patient.error.accountMissing':
      'Patient account is missing. Please log in again.',
  'patient.schedule.heroTitle': 'Appointments overview',
  'patient.schedule.heroSubtitle':
      'Track upcoming visits and review completed or cancelled bookings in one place.',
  'patient.schedule.filterPending': 'Pending',
  'patient.schedule.filterUpcoming': 'Upcoming',
  'patient.schedule.filterCompleted': 'Completed',
  'patient.schedule.filterCancelled': 'Cancelled',
  'patient.schedule.badge.pendingApproval': 'Pending approval',
  'patient.schedule.badge.upcoming': 'Upcoming',
  'patient.schedule.empty.pending': 'No pending appointments yet',
  'patient.schedule.empty.upcoming': 'No upcoming appointments yet',
  'patient.schedule.empty.completed': 'No completed appointments yet',
  'patient.schedule.empty.cancelled': 'No cancelled appointments yet',
  'patient.schedule.emptyHint':
      'Appointments appear here after you send a booking request.',
  'patient.schedule.serviceLabel': 'Service',
  'patient.schedule.completedAt': 'Completed: {date} · {time}',
  'patient.schedule.apiStatusRow': 'Status: {status}',
  'patient.schedule.providerIdFallback': 'Provider ID',
  'patient.schedule.specialtyUnavailable': 'Specialization unavailable',
  'patient.visitRating.sheetTitleNamed': 'Rate {name}',
  'patient.visitRating.shortScaleHint': 'How was your visit? (1–5 stars)',
  'patient.pay.paidByVisa': 'Paid by Visa',
  'patient.pay.paidByVisaMasked': 'Paid by Visa • **** {last4}',
  'patient.schedule.ratedBadge': 'Rated',
  'patient.namePrefixDoctor': 'Dr.',
  'patient.payConfirm.footerTotal': 'Total\n\$ {amount}',
  'patient.payConfirm.change': 'Change',
  'patient.payConfirm.sectionDate': 'Date',
  'patient.payConfirm.sectionReason': 'Reason',
  'patient.payConfirm.sectionVisitLocation': 'Visit location',
  'patient.payConfirm.sectionRequestInfo': 'Request info',
  'patient.payConfirm.urgentCase': 'Urgent case',
  'patient.payConfirm.defaultReason': 'General consultation',
  'patient.payConfirm.specialtyGeneralMedical': 'General medical care',
  'patient.payConfirm.specialtyHomeNursing': 'Home nursing care',
  'patient.payConfirm.lineConsultation': 'Consultation',
  'patient.payConfirm.lineAdminFee': 'Admin fee',
  'patient.payConfirm.lineDiscount': 'Additional discount',
  'patient.payConfirm.lineTotal': 'Total',
  'patient.payConfirm.dashPlaceholder': '-',
  'patient.payConfirm.bookingMissingId':
      'Booking was created but the appointment ID is missing.',
  'patient.messages.noneFound': 'No messages yet',
  'patient.pay.pending': 'Payment pending',
  'patient.pay.failed': 'Payment failed',
  'patient.pay.declined': 'Payment declined',
  'patient.pay.unpaid': 'Unpaid',
  'patient.pay.refunded': 'Refunded',
  'patient.payHist.chip.visit': 'Visit',
  'patient.pay.paid': 'Paid',
  'patient.provider.aboutServices': 'Services',
  'patient.provider.availableToday': 'Available today',
  'patient.provider.consultationFee': 'Consultation fee',
  'patient.title.paymentDetail': 'Payment detail',
  'patient.title.selectService': 'Select service',
  'patient.selectService.reviewNextSteps':
      'You can review and confirm everything in the next steps.',
  'patient.health.payStatus.failed': 'Failed',
  'patient.health.followUpRequired': 'Required',
  'patient.health.followUpRequiredBy': 'Required by {date}',
  'patient.profile.galleryPick': 'Choose from gallery',
  'patient.profile.photoPickSaveHint':
      'Photo selected — tap Save to apply.',
  'patient.profile.cameraUnavailable':
      'Camera not available. Try the gallery option.',
  'patient.profile.pickImageFail': 'Could not pick an image. Try again.',
  'patient.profile.requiredFieldsMissing':
      'Please fill all required fields.',
  'patient.profile.invalidLat':
      'Please enter a valid latitude.',
  'patient.profile.invalidLng':
      'Please enter a valid longitude.',
  'patient.profile.updatedSuccess': 'Profile updated successfully.',
  'patient.profile.genericErrorPrefix': 'Error:',
  'patient.profile.field.fullName': 'Full name',
  'patient.profile.field.chronicConditions': 'Chronic conditions',
  'patient.profile.placeholder.chronicShort':
      'Optional — ongoing conditions',
  'patient.profile.placeholder.allergiesShort':
      'Optional — drugs, foods, etc.',
  'patient.profile.placeholder.medsShort':
      'Optional — medicines and doses if known',
  'patient.request.continueCta': 'Continue',
  'patient.visa.payLabel': 'Visa · Demo',

  'patient.map.liveVisitTitle': 'Live visit map',
  'patient.map.whenProviderShares':
      'When the provider shares location, they appear here (refreshes every few seconds).',
  'patient.map.providerLastUpdate': 'Provider last update: {relative}',
  'patient.map.aboutKmAway': 'About {km} km away',
  'patient.map.aboutMAway': 'About {m} m away',

  'patient.availability.available': 'Available',
  'patient.availability.busy': 'Busy',
  'patient.distanceMeters': '{m} m',

  'patient.sortNearest': 'Nearest',
  'patient.sortPriceLow': 'Lowest price',
  'patient.providers.filterTitle': 'Filter providers',
  'patient.providers.providerType': 'Provider type',
  'patient.providers.specializationLabel': 'Specialization',
  'patient.providers.serviceTypeLabel': 'Service type',
  'patient.providers.availableNowSwitch': 'Available now only',
  'patient.providers.maxDistance': 'Max distance',
  'patient.providers.maxPrice': 'Max price (when shown)',
  'patient.providers.pickAnyOption': 'Any',
  'patient.providers.resultsLine': 'Results: {n} providers',
  'patient.providers.closestChip': 'Closest: {name}',
  'patient.providers.topRatedChip': 'Top rated: {rating}',
  'patient.providers.availableNowChip': 'Available now: {count}',
  'patient.providers.kmOnly': '{n} km',

  'notifications.title': 'Notifications',
  'notifications.readAll': 'Read all',
  'notifications.recent': 'Recent',
  'notifications.signInPrompt': 'Sign in to load your notifications.',
  'notifications.empty': 'No notifications yet',
  'notifications.emptySubtitle': 'You will see your updates here.',
  'notifications.serverSample':
      'Could not connect to the server. Showing sample notifications.',
  'notifications.relative.justNow': 'Just now',
  'notifications.relative.oneMinute': '1 min ago',
  'notifications.relative.minutes': '{n} min ago',
  'notifications.relative.oneHour': '1 hr ago',
  'notifications.relative.hours': '{n} hr ago',
  'notifications.relative.oneDay': '1 day ago',
  'notifications.relative.days': '{n} days ago',
  'notifications.fallbackBody':
      'You have a new notification for your CareLink account.',
  'notifications.fallbackNotification': 'Notification',
  'notifications.demo.confirmedTitle': 'Appointment Confirmed',
  'notifications.demo.confirmedBody': 'Your appointment has been confirmed.',
  'notifications.demo.messageTitle': 'New Message',
  'notifications.demo.messageBody': 'Doctor sent you a new message.',
  'notifications.demo.recordTitle': 'Medical Record Uploaded',
  'notifications.demo.recordBody': 'A new file was added to your records.',
  'notifications.demo.reminderTitle': 'Appointment Reminder',
  'notifications.demo.reminderBody': 'Appointment tomorrow at 10:00 AM.',
  'notifications.demo.securityTitle': 'Account Security',
  'notifications.demo.securityBody':
      'Your email was used to sign in on a new device.',
};

const Map<String, String> _ar = {
  'app.name': 'كيرلينك',
  'language.switchToArabic': 'العربية',
  'language.switchToEnglish': 'الإنجليزية',
  'theme.light': 'وضع فاتح',
  'theme.dark': 'وضع داكن',
  'intro.trustPill': 'موثوق. آمن. رعاية ذكية.',
  'intro.headline1': 'رعاية أفضل،',
  'intro.headline2': 'بترابط أسهل.',
  'intro.subtitle':
      'احصل على توصيات صحية ذكية، واحجز مزودي رعاية موثوقين، وأدر رحلتك الصحية من أي مكان.',
  'intro.getStarted': 'ابدأ الآن',
  'intro.aiInsights': 'رؤى ذكية',
  'intro.aiInsightsSubtitle': 'توصيات صحية ذكية',
  'intro.findProviders': 'ابحث عن مزودين',
  'intro.findProvidersSubtitle': 'احجز أطباء موثوقين',
  'intro.medications': 'الأدوية',
  'intro.medicationsSubtitle': 'إدارة وطلب الأدوية',
  'intro.healthRecords': 'السجلات الصحية',
  'intro.healthRecordsSubtitle': 'احفظ سجلاتك وادخل إليها',
  'intro.labTests': 'المختبر والفحوصات',
  'intro.labTestsSubtitle': 'احجز فحوصات واستلم التقارير',
  'intro.consultOnline': 'استشارة أونلاين',
  'intro.consultOnlineSubtitle': 'تواصل مع الأطباء من أي مكان',
  'intro.securePrivate': 'آمن وخاص',
  'intro.securePrivateSubtitle': 'بياناتك آمنة 100%',
  'intro.aiPowered': 'مدعوم بالذكاء',
  'intro.aiPoweredSubtitle': 'رؤى صحية أذكى',
  'intro.anywhereAccess': 'وصول من أي مكان',
  'intro.anywhereAccessSubtitle': 'الرعاية بين يديك',
  'auth.signIn': 'تسجيل الدخول',
  'auth.loginSubtitle': 'ادخل إلى حسابك لإدارة صحتك ومواعيدك.',
  'auth.email': 'البريد الإلكتروني',
  'auth.password': 'كلمة المرور',
  'auth.rememberMe': 'تذكرني',
  'auth.forgotPassword': 'نسيت كلمة المرور؟',
  'auth.forgotPasswordTitle': 'استعادة كلمة المرور',
  'auth.forgotPasswordBody':
      'أدخل بريدك الإلكتروني وسنرسل لك تعليمات إعادة تعيين كلمة المرور.',
  'auth.cancel': 'إلغاء',
  'auth.send': 'إرسال',
  'auth.orContinueWith': 'أو تابع باستخدام',
  'auth.noAccount': 'ليس لديك حساب؟ ',
  'auth.signUp': 'إنشاء حساب',
  'auth.loginSuccessful': 'تم تسجيل الدخول بنجاح',
  'auth.invalidServerUser':
      'استجابة الخادم غير صحيحة: بيانات المستخدم غير موجودة',
  'auth.enterEmailPassword': 'يرجى إدخال البريد الإلكتروني وكلمة المرور',
  'auth.enterValidEmail': 'يرجى إدخال بريد إلكتروني صحيح',
  'auth.enterEmail': 'يرجى إدخال بريدك الإلكتروني',
  'auth.resetSent':
      'إذا كان هذا البريد موجوداً، تم إرسال تعليمات إعادة التعيين.',
  'auth.doctorNotConnected': 'لوحة الطبيب غير مربوطة بعد',
  'auth.adminNotConnected': 'لوحة المدير غير مربوطة بعد',
  'auth.unknownRole': 'نوع المستخدم غير معروف: {role}',
  'auth.microsoftNotConnected':
      'تسجيل الدخول عبر Microsoft غير مربوط بعد. استخدم البريد أو Google / Apple.',
  'auth.comingSoon': 'قريباً',
  'auth.passwordRequired': 'يرجى إدخال كلمة المرور',
  'auth.checkForm': 'يرجى تصحيح الحقول المظللة.',
  'auth.emailNotRegistered': 'البريد الإلكتروني غير مسجل',
  'auth.checkEmail': 'تحقق من بريدك الإلكتروني لتعليمات إعادة التعيين.',
  'auth.chooseResetMethod': 'كيف تريد إعادة تعيين كلمة المرور؟',
  'auth.resetViaEmail': 'البريد الإلكتروني',
  'auth.resetViaPhone': 'الهاتف',
  'auth.phone': 'رقم الهاتف',
  'auth.enterPhone': 'أدخل رقم هاتفك',
  'auth.invalidPhone': 'أدخل 8–15 رقماً فقط',
  'auth.otpCode': 'رمز التحقق',
  'auth.sendCode': 'إرسال الرمز',
  'auth.resendIn': 'أعد الإرسال خلال {seconds} ث',
  'auth.resendCode': 'إعادة إرسال الرمز',
  'auth.verifyAndContinue': 'تحقق من الرمز',
  'auth.invalidOtp': 'رمز غير صحيح أو منتهي',
  'auth.newPassword': 'كلمة المرور الجديدة',
  'auth.confirmNewPassword': 'تأكيد كلمة المرور',
  'auth.resetPassword': 'تحديث كلمة المرور',
  'auth.phoneNotRegistered': 'رقم الهاتف غير مسجل',
  'auth.passwordsNoMatch': 'كلمتا المرور غير متطابقتين',
  'auth.verifying': 'جاري التحقق…',
  'auth.devOtpHint': 'رمز التجربة: {code}',
  'auth.verificationCodeSentEmail': 'تم إرسال رمز التحقق إلى بريدك',
  'auth.verificationCodeSentPhone': 'تم إرسال رمز التحقق إلى هاتفك',
  'auth.invalidVerificationCode': 'رمز التحقق غير صحيح',
  'auth.emailVerifiedSuccess': 'تم التحقق من البريد الإلكتروني بنجاح',
  'auth.phoneVerifiedSuccess': 'تم التحقق من الهاتف بنجاح',
  'auth.enterCodeHint':
      'أدخل الرمز المكوّن من 6 أرقام. ينتهي خلال 5 دقائق.',
  'auth.forgotPasswordEmailSubtitle':
      'سنرسل رمزاً إلى بريدك لتأكيد أنك تملك هذا العنوان.',
  'auth.forgotPasswordPhoneSubtitle':
      'سنرسل رمزاً عبر الرسائل (عند التفعيل) لتأكيد رقمك.',
  'auth.verifyEmailFirst': 'تحقق من بريدك بالرمز المرسل قبل إنشاء الحساب.',
  'auth.verifyPhoneFirst': 'تحقق من هاتفك بالرمز المرسل قبل إنشاء الحساب.',
  'patient.allProviders': 'كل مزودي الرعاية',
  'patient.voiceUnavailable': 'الإدخال الصوتي غير متاح على هذا الجهاز.',
  'patient.typeCareNeed': 'اكتب أو قل نوع الرعاية التي تحتاجها، ثم اضغط بحث.',
  'patient.providersLoading': 'قائمة المزودين ما زالت تتحمل - حاول بعد قليل.',
  'patient.goodMorning': 'صباح الخير',
  'patient.goodAfternoon': 'مساء الخير',
  'patient.goodEvening': 'مساء الخير',
  'patient.recommendedForYou': 'موصى به لك',
  'patient.typeOrSpeak':
      'اكتب أو تحدث عن حاجتك. لتوصية أدق، أضف سجلك الطبي من الملف الشخصي > السجلات الطبية.',
  'patient.recommended': 'موصى به: {provider}',
  'patient.find': 'بحث',
  'patient.stopVoice': 'إيقاف الإدخال الصوتي',
  'patient.speakNeed': 'تحدث عن الرعاية التي تحتاجها',
  'patient.signInEditProfile': 'سجل الدخول لتعديل ملفك الشخصي.',
  'patient.hiLoading': 'أهلاً...',
  'patient.hiName': 'أهلاً، {name}',
  'patient.bookNextVisit': 'احجز زيارتك القادمة',
  'patient.homeNursingCare': 'رعاية تمريض منزلية',
  'patient.trustedCare': 'رعاية موثوقة',
  'patient.book': 'حجز',
  'patient.badgeRecommended': 'موصى به',
  'patient.hiFallback': 'صديقنا',
  'patient.homeWelcomeSubline': '{greeting}، {welcome}',
  'patient.homeLocationPrefix': 'الموقع',
  'patient.homeLocationResolving': 'جاري تحديد موقعك…',
  'patient.homeLocationUnavailable':
      'فعّل الموقع أو أضف عنوانك من الملف الشخصي.',
  'patient.careProviderGeneric': 'مزود رعاية',
  'patient.providersEmptyFilters': 'لا يوجد مزودون يطابقون التصفية.',
  'patient.providersLoadFailed':
      'تعذّر تحميل المزودين. حاول مرة أخرى.',
  'patient.distanceAwayKm': 'على بُعد {km} كم',
  'patient.navHome': 'الرئيسية',
  'patient.navCare': 'رعايتي',
  'patient.navChat': 'الدردشة',
  'patient.navProfile': 'الملف',
  'patient.listening': 'أستمع',
  'patient.listeningRequest': 'أستمع إلى طلبك',
  'patient.askAi': 'اسأل ذكاء CareLink',
  'patient.sayOrType': 'قل أو اكتب نوع الرعاية لترتيب المزودين.',
  'nurse.title': 'كيرلينك - الممرض',
  'nurse.dashboard': 'اللوحة',
  'nurse.requests': 'الطلبات',
  'nurse.reports': 'التقارير',
  'nurse.payments': 'المدفوعات',
  'nurse.settings': 'الإعدادات',
  'nurse.welcome': 'أهلاً، {name}',
  'nurse.matter': 'خدماتك الصحية تصنع فرقاً',
  'nurse.quickOverview': 'نظرة سريعة',
  'nurse.pendingRequests': 'طلبات قيد الانتظار',
  'nurse.todaysVisits': 'زيارات اليوم',
  'nurse.completed': 'مكتملة',
  'nurse.earnings': 'الأرباح',
  'nurse.quickActions': 'إجراءات سريعة',
  'nurse.profile': 'الملف المهني',
  'nurse.profileSubtitle': 'حدّث ملفك المهني',
  'nurse.serviceRequests': 'طلبات الخدمة',
  'nurse.serviceRequestsSubtitle': 'اقبل أو ارفض الطلبات الجديدة',
  'nurse.submitReport': 'إرسال تقرير',
  'nurse.submitReportSubtitle': 'وثّق الزيارات المكتملة',
  'nurse.paymentHistory': 'سجل المدفوعات',
  'nurse.paymentHistorySubtitle': 'راجع الأرباح والمدفوعات',
  'nurse.settingsSubtitle': 'إدارة الملف والتفضيلات',

  'payment.line.unpaidPay':
      'الدفع: فيزا — أكمل الدفع ببطاقة فيزا. لا يُقبل النقد.',
  'payment.line.unpaidNext':
      'الدفع: فيزا — ستدفع ببطاقة فيزا في الخطوة التالية. لا يُقبل النقد.',
  'payment.line.paid': 'الدفع: تم الدفع عبر فيزا',
  'payment.line.paidLast4': 'الدفع: تم الدفع بفيزا • **** {last4}',
  'payment.payWithVisa': 'ادفع بفيزا',
  'payment.completeTitle': 'إتمام الدفع',
  'payment.completeSubtitleDemo':
      'تجريبي: بطاقات فيزا التجارية المعتمدة فقط — بدون رسوم حقيقية.',
  'payment.visaCheckout': 'دفع فيزا',
  'payment.visaOnlyNote':
      'فيزا فقط. ستُدخل تفاصيل البطاقة في الخطوة التالية — لا نخزّن الرقم الكامل أو الـCVV.',
  'payment.openingCheckout': 'جاري فتح الدفع…',
  'payment.successPaid': 'تم الدفع بنجاح',
  'payment.successRecorded': 'تم تسجيل الدفع',
  'payment.demoNoCharge': 'تجريبي — بدون رسوم حقيقية.',
  'payment.pendingCheckout': 'دفع الفيزا ما زال قيد الإتمام.',
  'payment.savedBooking': 'تم حفظ تفاصيل الحجز.',
  'payment.summary.appointment': 'الموعد',
  'payment.summary.amount': 'المبلغ',
  'payment.backHome': 'العودة للرئيسية',
  'payment.amountPositive': 'يجب أن يكون المبلغ أكبر من صفر.',
  'payment.notCompleted': 'لم يكتمل الدفع.',
  'payment.genericError': 'حدث خطأ ما.',
  'payment.demoLedgerNote':
      'تجريبي فيزا — بطاقات تجريبية فقط. لا نخزّن الرقم الكامل أو الـCVV.',

  'securePayment.title': 'دفع فيزا آمن',
  'securePayment.b1':
      'اتصال مشفّر بين جهازك وكيرلينك.',
  'securePayment.b2':
      'لا نخزّن الرقم الكامل أو الـCVV أو الصلاحية — فقط معلومات آمنة مثل نوع الفيزا وآخر أربعة أرقام.',
  'securePayment.b3':
      'الوضع التجريبي يستخدم بطاقات فيزا تجريبية فقط؛ لا مفاتيح معالج دفع داخل التطبيق.',
  'securePayment.b4':
      'فيزا فقط — لا يُقبل النقد أو طرق أخرى.',

  'patient.title.profile': 'الملف الشخصي',
  'patient.title.reviewBooking': 'مراجعة الحجز',
  'patient.title.visitReport': 'تقرير الزيارة',
  'patient.title.appointment': 'موعد',
  'patient.title.payment': 'الدفع',
  'patient.title.bookingDetails': 'تفاصيل الحجز',
  'patient.title.healthRecord': 'الملف الصحي',
  'patient.title.paymentHistory': 'سجل المدفوعات',
  'patient.title.findProviders': 'بحث عن مزودين',
  'patient.title.schedule': 'جدولي',
  'patient.title.myCare': 'رعايتي',
  'patient.careHub.introTitle': 'المواعيد والملف الصحي',
  'patient.careHub.introBody':
      'نظّم زياراتك، حافظ على ملفك الطبي، واستخدم تقارير الزيارة لخط زمني طويل المدى (أعراض وملاحظات لكل زيارة).',
  'patient.careHub.scheduleTitle': 'جدول المواعيد',
  'patient.careHub.scheduleSubtitle': 'صفِّ حسب الحالة وافتح كل حجز',
  'patient.careHub.recordsTitle': 'السجلات الطبية',
  'patient.careHub.recordsSubtitle': 'ملف إلكتروني؛ أضف أو عدّل البيانات',
  'patient.careHub.linkVisitReports': 'تقارير الزيارة (طويل الأمد)',
  'patient.careHub.linkSimpleList': 'القادمة والسجل (قائمة بسيطة)',
  'patient.careHub.documentedTitle': 'الزيارات المسجلة',
  'patient.careHub.documentedSubtitle':
      'الزيارات المكتملة والملغاة تظل مدرجة لسجلاتك.',
  'patient.careHub.emptyVisits':
      'لا توجد زيارات سابقة بعد. عند إكمال الزيارات أو إلغائها تظهر هنا.',

  'patient.appointments.header': 'المواعيد',
  'patient.tab.upcoming': 'القادمة',
  'patient.tab.history': 'السجل',
  'patient.noAppointments': 'لا توجد مواعيد.',
  'patient.dateUnavailable': 'التاريخ غير متاح',
  'patient.timeUnavailable': 'الوقت غير متاح',
  'patient.providerFallback': 'مزود',
  'patient.role.doctor': 'طبيب',
  'patient.role.nurse': 'ممرض',
  'patient.rateVisitHint': 'اضغط لتقييم الزيارة',
  'patient.status.pending': 'قيد الانتظار',
  'patient.status.confirmed': 'مؤكد',
  'patient.status.completed': 'مكتمل',
  'patient.status.cancelled': 'ملغى',

  'patient.messages.header': 'الرسائل',
  'patient.searchMessagesHint': 'بحث في الرسائل…',
  'patient.noMessagesFound': 'لم يتم العثور على رسائل',

  'patient.profile.noName': 'بدون اسم',
  'patient.profile.noEmail': 'بدون بريد',
  'patient.profile.accountType': 'نوع الحساب',
  'patient.profile.deleteNote':
      'تعطيل/حذف الحساب سيُضاف لاحقاً عبر مسار آمن.',
  'patient.menu.editProfile': 'تعديل الملف',
  'patient.menu.medicalRecords': 'السجلات الطبية',
  'patient.menu.paymentHistoryMenu': 'سجل المدفوعات',
  'patient.menu.notifications': 'الإشعارات',
  'patient.menu.logout': 'تسجيل الخروج',
  'patient.field.email': 'البريد الإلكتروني',
  'patient.field.phone': 'الهاتف',
  'patient.field.address': 'العنوان',
  'patient.field.dob': 'تاريخ الميلاد',
  'patient.field.gender': 'الجنس',
  'patient.healthTab.records': 'السجلات',
  'patient.healthTab.profile': 'الملف الصحي',
  'patient.healthTab.timeline': 'الخط الزمني',
  'patient.healthBaseline.title': 'الملف الصحي الأساسي',
  'patient.healthBaseline.body':
      'حافظ على تحديث الأمراض المزمنة والحساسية والأدوية. '
      'هذا يدعم رعاية أكثر أماناً وتوصيات أفضل. '
      'التشخيصات الرسمية بعد الزيارات تظهر في تبويب السجلات.',
  'patient.healthBaseline.editCta': 'تعديل الملف والأساس الصحي',
  'patient.profileCard.ageDob': 'العمر / تاريخ الميلاد',
  'patient.profileCard.chronicConditions': 'حالات مزمنة',
  'patient.profileCard.allergies': 'الحساسية',
  'patient.profileCard.medications': 'الأدوية الحالية',

  'patient.welcomeBack': 'أهلاً بعودتك!',
  'patient.upcomingAppointment': 'الموعد القادم',
  'patient.viewDetailsGt': 'عرض التفاصيل >',
  'patient.browsePopularProviders': 'تصفح مزودي الرعاية أدناه',
  'patient.consultation': 'استشارة',
  'patient.favorites': 'المفضلة',
  'patient.seeAllGt': 'عرض الكل >',
  'patient.providerSpecialty': 'تخصص المزود',
  'patient.popularProviders': 'مزودون رائجون',
  'patient.smartMatchExplainerFull':
      'المطابقة الذكية تستخدم حالتك الحالية والملف الطبي والتخصص والمسافة والتوفر والتقييمات والخبرة.',
  'patient.smartMatchExplainerAddRecord':
      'أضف سجلًا طبيًا أو صف حاجتك لمطابقات أوضح.',
  'patient.aiCareMatch': 'مطابقة رعاية بالذكاء',
  'patient.aiMedicalFileHint':
      'يُفعّل الملف الطبي المحفوظ ضمن النتيجة (الأمراض والحساسية مقابل تخصص المزود) مع المسافة والتوفر والتقييمات والخبرة.',
  'patient.aiSmartMatchFallback': 'مطابقة ذكية',
  'patient.careSearchHint':
      'مثال: متابعة سكري، أطفال، قلب، متوفر الآن',
  'patient.notificationsTooltip': 'الإشعارات',
  'patient.sortSmart': 'مطابقة ذكية',
  'patient.sortTopRated': 'الأعلى تقييماً',
  'patient.sortAz': 'أ-ي',
  'patient.filterAll': 'الكل',
  'patient.filterAvailableNow': 'متوفر الآن',
  'patient.reschedule': 'إعادة جدولة',
  'patient.joinNow': 'انضم الآن',
  'patient.paymentHistory.empty': 'لا توجد مدفوعات بعد.',

  'patient.action.tryAgain': 'حاول مرة أخرى',
  'patient.action.apply': 'تطبيق',
  'patient.action.reset': 'إعادة ضبط',
  'patient.action.continue': 'متابعة',
  'patient.action.saveChanges': 'حفظ التغييرات',
  'patient.providers.searchHint': 'ابحث عن طبيب أو ممرض أو تخصص',
  'patient.providers.loadFailedShort': 'تعذّر تحميل المزودين.',
  'patient.providers.noMatchFilters':
      'لا يوجد مزودون يطابقون البحث أو التصفية.',
  'patient.providers.minRating': 'أدنى تقييم: {value}',
  'patient.location.useCurrent': 'استخدام الموقع الحالي',
  'patient.location.placeHint':
      'اكتب المدينة أو المكان ثم اختر النتيجة',
  'patient.location.confirm': 'تأكيد الموقع',
  'patient.location.pickVisitSubtitle': 'حدد موعد زيارة المزود لك',
  'patient.selectService.title': 'ما نوع الخدمة التي تحتاجها؟',
  'patient.selectService.subtitle': 'اختر الخدمة الأنسب لحالتك.',
  'patient.service.homeNursing.title': 'تمريض منزلي',
  'patient.service.homeNursing.desc': 'رعاية تمريضية ماهرة في منزلك.',
  'patient.service.wound.title': 'عناية الجروح',
  'patient.service.wound.desc': 'تغيير ضمادات وإدارة الجروح باحتراف.',
  'patient.service.injection.title': 'حقن',
  'patient.service.injection.desc': 'إعطاء أدوية بواسطة ممرض مؤهل.',
  'patient.service.elderly.title': 'رعاية كبار السن',
  'patient.service.elderly.desc': 'دعم يومي محترم للراحة والصحة.',
  'patient.service.docConsult.title': 'استشارة طبيب',
  'patient.service.docConsult.desc': 'زيارة طبيب عن بُعد أو حضورياً.',
  'patient.service.followup.title': 'زيارة متابعة',
  'patient.service.followup.desc': 'متابعة التقدّم واستمرار الرعاية.',
  'patient.request.reasonVisit': 'سبب الزيارة',
  'patient.request.symptomsOptional': 'الأعراض (اختياري)',
  'patient.request.notesOptional': 'ملاحظات إضافية (اختياري)',
  'patient.booking.pickDateTime': 'يرجى اختيار التاريخ والوقت أولاً.',
  'patient.booking.chooseDateTimeSubtitle': 'اختر التاريخ والوقت المناسبين.',
  'patient.booking.timesShownLocal':
      'الأوقات المعروضة بتوقيت جهازك المحلي.',
  'patient.request.currentCase': 'الحالة الحالية',
  'patient.request.currentCaseBody':
      'هذا خاص بهذا الحجز فقط. يستخدمه المزود للتحضير، ويساعد المحرك على مطابقة أفضل.',
  'patient.request.reasonPlaceholder': 'صف سبب الزيارة',
  'patient.request.symptomsPlaceholder': 'صف أي أعراض تشعر بها',
  'patient.request.additionalPlaceholder':
      'أي معلومات أخرى ترغب بمشاركتها',
  'patient.request.urgentTitle': 'هل هذا عاجل؟',
  'patient.request.urgentSub':
      'سنعطي طلبك أولوية قدر الإمكان.',
  'patient.request.detailsHeaderTitle': 'تفاصيل الحالة',
  'patient.request.detailsSubtitle': 'أخبرنا بما تحتاجه لهذه الزيارة',
  'patient.request.infoStripDetailed':
      'التفاصيل تساعد مزود الرعاية على التحضير للزيارة.',
  'patient.request.confidentialLine': 'معلوماتك تُعامل بسرّية.',
  'patient.chat.hintMessage': 'اكتب رسالة…',
  'patient.visitReport.submit': 'إرسال التقرير',
  'patient.visitReport.needDiagnosis': 'أضف تشخيصاً أو خطة علاج.',
  'patient.visitReport.vitalsInvalidJson':
      'يجب أن تكون العلامات الحيوية بتنسيق JSON صالح.',
  'patient.visitReport.visitDate': 'تاريخ الزيارة',
  'patient.visitReport.medsPrescribed': 'أدوية موصوفة (اختياري)',
  'patient.visitReport.allergiesNotedVisit':
      'حساسيات مذكورة في الزيارة (اختياري)',
  'patient.visitReport.vitalsJsonLabel': 'علامات حيوية (JSON)',
  'patient.visitReport.diagnosis': 'التشخيص',
  'patient.visitReport.treatmentPlan': 'خطة العلاج',
  'patient.visitReport.recommendations': 'التوصيات',
  'patient.visitReport.followUpDate': 'تاريخ المتابعة',
  'patient.record.block.vitals': 'العلامات الحيوية',
  'patient.record.block.diagnosis': 'التشخيص',
  'patient.record.block.treatmentPlan': 'خطة العلاج',
  'patient.record.block.recommendations': 'التوصيات',
  'patient.record.block.meds': 'الأدوية',
  'patient.record.block.allergiesVisit': 'الحساسية (الزيارة)',
  'patient.record.block.notes': 'ملاحظات',
  'patient.record.block.followUp': 'متابعة',
  'patient.booking.cancelSuccess': 'تم إلغاء الموعد بنجاح.',
  'patient.booking.cancelCta': 'إلغاء الحجز',
  'patient.booking.cancelReasonApp': 'أُلغي من التطبيق',
  'patient.pay.amountUnavailable':
      'المبلغ غير متاح. أكمل الدفع من مسار تأكيد الحجز.',
  'patient.pay.careVisit': 'زيارة رعاية',
  'patient.pay.amountAtCheckout': 'يُحدد المبلغ عند الدفع ({currency})',
  'patient.pay.statusLine': 'الحالة: {status}',
  'patient.booking.banner.acceptTitle': 'مقبول — الزيارة في موعدها',
  'patient.booking.banner.acceptSub':
      'يمكنك تتبّع المزود على الخريطة عند مشاركة الموقع المباشر.',
  'patient.booking.banner.pendingTitle': 'بانتظار رد المزود',
  'patient.booking.banner.pendingSub':
      'قد يقبل المزود أو يرفض. سنعلمك هنا.',
  'patient.booking.banner.completedTitle': 'تمت الزيارة',
  'patient.booking.banner.completedSub':
      'قيّم مزودك بعد الخدمة — يساعد ذلك التوصيات لاحقاً.',
  'patient.detail.provider': 'المزود',
  'patient.detail.role': 'الدور',
  'patient.detail.specialization': 'التخصص',
  'patient.detail.dateTime': 'التاريخ والوقت',
  'patient.detail.status': 'الحالة',
  'patient.detail.notes': 'ملاحظات',
  'patient.detail.location': 'الموقع',
  'patient.detail.visitAddress': 'عنوان الزيارة',
  'patient.detail.locationNote': 'ملاحظة الموقع',
  'patient.detail.symptoms': 'الأعراض',
  'patient.detail.urgency': 'الأولوية',
  'patient.detail.urgencyUrgent': 'عاجل',
  'patient.detail.urgencyNormal': 'عادي',
  'patient.visitRating.title': 'تقييمك',
  'patient.visitRating.ratePrompt': 'قيّم هذه الزيارة',
  'patient.visitRating.scaleExplain':
      '1 ضعيف — 5 ممتاز. يحدّث ذلك درجات المزود ضمن المطابقة الذكية.',
  'patient.visitRating.optionalComment': 'تعليق اختياري',
  'patient.visitRating.pickStars': 'اختر عدد النجوم من 1 إلى 5.',
  'patient.visitRating.submitBtn': 'إرسال التقييم',
  'patient.visitRating.thanks': 'شكراً! تقييمك يحسّن التوصيات للجميع.',
  'patient.schedule.ratingSavedThanks': 'شكراً — تم حفظ تقييمك.',
  'patient.schedule.rateProvider': 'تقييم المزود',
  'patient.schedule.scheduledDate': 'تاريخ الموعد',
  'patient.schedule.scheduledTime': 'وقت الموعد',
  'patient.schedule.paymentPrefix': 'الدفع: {detail}',
  'patient.schedule.cancelledBadge': 'ملغى',
  'patient.error.accountMissing': 'لا يوجد حساب مريض. الرجاء تسجيل الدخول مجدداً.',
  'patient.schedule.heroTitle': 'نظرة على المواعيد',
  'patient.schedule.heroSubtitle':
      'تابع المواعيد القادمة وراجع المواعيد المكتملة أو الملغاة في مكان واحد.',
  'patient.schedule.filterPending': 'معلقة',
  'patient.schedule.filterUpcoming': 'قادمة',
  'patient.schedule.filterCompleted': 'مكتملة',
  'patient.schedule.filterCancelled': 'ملغاة',
  'patient.schedule.badge.pendingApproval': 'بانتظار الموافقة',
  'patient.schedule.badge.upcoming': 'قادمة',
  'patient.schedule.empty.pending': 'لا توجد مواعيد معلقة',
  'patient.schedule.empty.upcoming': 'لا توجد مواعيد قادمة',
  'patient.schedule.empty.completed': 'لا توجد مواعيد مكتملة',
  'patient.schedule.empty.cancelled': 'لا توجد مواعيد ملغاة',
  'patient.schedule.emptyHint':
      'تظهر المواعيد هنا بعد إرسال طلب حجز.',
  'patient.schedule.serviceLabel': 'الخدمة',
  'patient.schedule.completedAt': 'اكتمال: {date} · {time}',
  'patient.schedule.apiStatusRow': 'الحالة: {status}',
  'patient.schedule.providerIdFallback': 'معرّف مقدّم الخدمة',
  'patient.schedule.specialtyUnavailable': 'التخصص غير متاح',
  'patient.visitRating.sheetTitleNamed': 'قيّم {name}',
  'patient.visitRating.shortScaleHint':
      'كيف كانت زيارتك؟ (1–5 نجوم)',
  'patient.pay.paidByVisa': 'مدفوع بفيزا',
  'patient.pay.paidByVisaMasked': 'مدفوع بفيزا • **** {last4}',
  'patient.schedule.ratedBadge': 'تم التقييم',
  'patient.namePrefixDoctor': 'د.',
  'patient.payConfirm.footerTotal': 'الإجمالي\n{amount} \$',
  'patient.payConfirm.change': 'تغيير',
  'patient.payConfirm.sectionDate': 'التاريخ',
  'patient.payConfirm.sectionReason': 'السبب',
  'patient.payConfirm.sectionVisitLocation': 'موقع الزيارة',
  'patient.payConfirm.sectionRequestInfo': 'تفاصيل الطلب',
  'patient.payConfirm.urgentCase': 'حالة عاجلة',
  'patient.payConfirm.defaultReason': 'استشارة عامة',
  'patient.payConfirm.specialtyGeneralMedical': 'رعاية طبية عامة',
  'patient.payConfirm.specialtyHomeNursing': 'تمريض منزلي',
  'patient.payConfirm.lineConsultation': 'استشارة',
  'patient.payConfirm.lineAdminFee': 'رسوم إدارية',
  'patient.payConfirm.lineDiscount': 'خصم إضافي',
  'patient.payConfirm.lineTotal': 'الإجمالي',
  'patient.payConfirm.dashPlaceholder': '—',
  'patient.payConfirm.bookingMissingId':
      'تم إنشاء الحجز ولكن معرّف الموعد غير موجود.',
  'patient.messages.noneFound': 'لا توجد رسائل بعد',
  'patient.pay.pending': 'الدفع قيد المعالجة',
  'patient.pay.failed': 'فشل الدفع',
  'patient.pay.declined': 'رفض الدفع',
  'patient.pay.unpaid': 'غير مدفوع',
  'patient.pay.refunded': 'مسترد',
  'patient.payHist.chip.visit': 'زيارة',
  'patient.pay.paid': 'مدفوع',
  'patient.provider.aboutServices': 'الخدمات',
  'patient.provider.availableToday': 'متاح اليوم',
  'patient.provider.consultationFee': 'رسوم الاستشارة',
  'patient.title.paymentDetail': 'تفاصيل الدفع',
  'patient.title.selectService': 'اختر الخدمة',
  'patient.selectService.reviewNextSteps':
      'يمكنك مراجعة وتأكيد كل التفاصيل في الخطوات التالية.',
  'patient.health.payStatus.failed': 'فشل',
  'patient.health.followUpRequired': 'مطلوب',
  'patient.health.followUpRequiredBy': 'مطلوب بحلول {date}',
  'patient.profile.galleryPick': 'اختيار من المعرض',
  'patient.profile.photoPickSaveHint':
      'تم اختيار صورة — اضغط حفظ للتطبيق.',
  'patient.profile.cameraUnavailable':
      'الكاميرا غير متاحة. جرّب المعرض.',
  'patient.profile.pickImageFail':
      'تعذّر اختيار صورة. حاول مرة أخرى.',
  'patient.profile.requiredFieldsMissing':
      'يرجى تعبئة جميع الحقول المطلوبة.',
  'patient.profile.invalidLat': 'يرجى إدخال خط عرض صالح.',
  'patient.profile.invalidLng': 'يرجى إدخال خط طول صالح.',
  'patient.profile.updatedSuccess': 'تم تحديث الملف بنجاح.',
  'patient.profile.genericErrorPrefix': 'خطأ:',
  'patient.profile.field.fullName': 'الاسم الكامل',
  'patient.profile.field.chronicConditions': 'الأمراض المزمنة',
  'patient.profile.placeholder.chronicShort':
      'اختياري — الحالات المستمرة',
  'patient.profile.placeholder.allergiesShort':
      'اختياري — أدوية، أطعمة، إلخ',
  'patient.profile.placeholder.medsShort':
      'اختياري — الأدوية والجرعات إن وجدت',
  'patient.request.continueCta': 'متابعة',
  'patient.visa.payLabel': 'فيزا · تجريبي',

  'patient.map.liveVisitTitle': 'خريطة الزيارة المباشرة',
  'patient.map.whenProviderShares':
      'عند مشاركة المزود موقعه، يظهر هنا (يتحدّث كل بضع ثوانٍ).',
  'patient.map.providerLastUpdate': 'آخر تحديث للمزود: {relative}',
  'patient.map.aboutKmAway': 'على بعد نحو {km} كم',
  'patient.map.aboutMAway': 'على بعد نحو {m} م',

  'patient.availability.available': 'متاح',
  'patient.availability.busy': 'مشغول',
  'patient.distanceMeters': '{m} م',

  'patient.sortNearest': 'الأقرب',
  'patient.sortPriceLow': 'الأقل سعراً',
  'patient.providers.filterTitle': 'تصفية المزودين',
  'patient.providers.providerType': 'نوع المزود',
  'patient.providers.specializationLabel': 'التخصص',
  'patient.providers.serviceTypeLabel': 'نوع الخدمة',
  'patient.providers.availableNowSwitch': 'المتاحون الآن فقط',
  'patient.providers.maxDistance': 'أقصى مسافة',
  'patient.providers.maxPrice': 'أقصى سعر (عند العرض)',
  'patient.providers.pickAnyOption': 'أي',
  'patient.providers.resultsLine': 'النتائج: {n} مزوداً',
  'patient.providers.closestChip': 'الأقرب: {name}',
  'patient.providers.topRatedChip': 'الأعلى تقييماً: {rating}',
  'patient.providers.availableNowChip': 'متوفر الآن: {count}',
  'patient.providers.kmOnly': '{n} كم',

  'notifications.title': 'الإشعارات',
  'notifications.readAll': 'تعليم الكل كمقروء',
  'notifications.recent': 'الأحدث',
  'notifications.signInPrompt': 'سجّل الدخول لتحميل إشعاراتك.',
  'notifications.empty': 'لا إشعارات بعد',
  'notifications.emptySubtitle': 'ستظهر التحديثات هنا.',
  'notifications.serverSample':
      'تعذّر الاتصال بالخادم. عرض إشعارات تجريبية.',
  'notifications.relative.justNow': 'الآن',
  'notifications.relative.oneMinute': 'منذ دقيقة',
  'notifications.relative.minutes': 'منذ {n} د',
  'notifications.relative.oneHour': 'منذ ساعة',
  'notifications.relative.hours': 'منذ {n} س',
  'notifications.relative.oneDay': 'منذ يوم',
  'notifications.relative.days': 'منذ {n} أيام',
  'notifications.fallbackBody':
      'لديك إشعار جديد لحسابك في كيرلينك.',
  'notifications.fallbackNotification': 'إشعار',
  'notifications.demo.confirmedTitle': 'تم تأكيد الموعد',
  'notifications.demo.confirmedBody': 'تم تأكيد موعدك.',
  'notifications.demo.messageTitle': 'رسالة جديدة',
  'notifications.demo.messageBody': 'أرسل لك الطبيب رسالة.',
  'notifications.demo.recordTitle': 'تم رفع سجل طبي',
  'notifications.demo.recordBody': 'أُضيف ملف إلى سجلاتك.',
  'notifications.demo.reminderTitle': 'تذكير بالموعد',
  'notifications.demo.reminderBody': 'موعدك غداً الساعة 10:00.',
  'notifications.demo.securityTitle': 'أمان الحساب',
  'notifications.demo.securityBody':
      'استُخدم بريدك لتسجيل الدخول من جهاز جديد.',
};
