import 'package:flutter/widgets.dart';

class CarelinkL10n {
  const CarelinkL10n(this.locale);

  final Locale locale;

  bool get isArabic => locale.languageCode == 'ar';

  static CarelinkL10n of(BuildContext context) {
    return CarelinkL10n(Localizations.localeOf(context));
  }

  String t(String key, {Map<String, String>? args}) {
    var value = (isArabic ? _ar : _en)[key] ?? _en[key] ?? key;
    if (args != null) {
      for (final entry in args.entries) {
        value = value.replaceAll('{${entry.key}}', entry.value);
      }
    }
    return value;
  }
}

extension CarelinkL10nX on BuildContext {
  CarelinkL10n get l10n => CarelinkL10n.of(this);

  String tr(String key, {Map<String, String>? args}) {
    return l10n.t(key, args: args);
  }
}

const Map<String, String> _en = {
  'booking.step.service': 'Service',
  'booking.step.dateTime': 'Date & Time',
  'booking.step.location': 'Location',
  'booking.step.details': 'Details',
  'booking.step.review': 'Review',
  'booking.selectService.title': 'Select service',
  'booking.selectService.subtitle': 'Choose the care you need',
  'booking.selectService.prompt': 'What type of care do you need?',
  'booking.selectService.promptSubtitle':
      'Choose a service and then select an available provider.',
  'booking.appointmentType': 'Appointment type',
  'booking.homeVisit': 'Home visit',
  'booking.remoteConsultation': 'Remote consultation',
  'booking.chooseProvider': 'Choose provider',
  'booking.loadingProviders': 'Loading providers...',
  'booking.noProvidersForService':
      'No providers are available for this service right now.',
  'booking.providerUnavailable': 'This provider is currently not available.',
  'booking.continue': 'Continue',
  'booking.tryAgain': 'Try again',
  'booking.service.homeNursing': 'Home nursing',
  'booking.service.homeNursing.desc':
      'Skilled care at your residence with nursing support.',
  'booking.service.generalDoctor': 'General doctor',
  'booking.service.generalDoctor.desc':
      'Medical consultation and general health guidance.',
  'booking.service.postSurgery': 'Post-surgery care',
  'booking.service.postSurgery.desc':
      'Follow-up support after medical procedures.',
  'booking.service.elderlyCare': 'Elderly care',
  'booking.service.elderlyCare.desc':
      'Respectful support for daily health and comfort.',
  'booking.service.physiotherapy': 'Physiotherapy',
  'booking.service.physiotherapy.desc':
      'Mobility, recovery, and rehabilitation support.',
  'booking.service.mentalSupport': 'Mental support',
  'booking.service.mentalSupport.desc':
      'Remote emotional support and wellbeing guidance.',
  'booking.dateTime.title': 'Select date & time',
  'booking.dateTime.subtitle': 'Pick your visit slot',
  'booking.dateTime.prompt': 'Choose your preferred date and time',
  'booking.dateTime.promptSubtitle':
      'Available times are shown from provider availability.',
  'booking.dateTime.chooseFirst': 'Please choose date and time first',
  'booking.dateTime.notAvailable': 'This provider is currently not available.',
  'booking.dateTime.chooseAnotherProvider':
      'Please choose another provider to continue booking.',
  'booking.dateTime.selectDate': 'Select date',
  'booking.dateTime.selectTime': 'Select time',
  'booking.dateTime.noTimes': 'No available times for this date.',
  'booking.dateTime.approx': 'All times are approximate and may vary.',
  'booking.dateTime.monthHelp': 'Select month and year',
  'booking.location.title': 'Choose address',
  'booking.location.chooseAddress': 'Choose address',
  'booking.location.useThisAddress': 'Use this address',
  'booking.location.subtitle': 'Choose where the provider will visit you',
  'booking.location.confirm': 'Confirm location',
  'booking.location.useCurrent': 'Use current location',
  'booking.location.adjust': 'Drag the map to adjust location',
  'booking.location.address': 'Address',
  'booking.location.addressHint': 'Type city/place name and choose result',
  'booking.location.note': 'Location note (optional)',
  'booking.location.noteHint': 'Apartment, floor, entrance, or nearby landmark',
  'booking.location.private': 'Your location is only used for this booking',
  'booking.case.title': 'Current case',
  'booking.case.subtitle': 'Tell us what you need for this visit',
  'booking.case.prompt': 'Current case',
  'booking.case.promptSubtitle':
      'This helps the provider prepare for your booking.',
  'booking.case.reason': 'Reason for visit',
  'booking.case.reasonHint': 'Please describe the reason for your visit',
  'booking.case.symptoms': 'Symptoms (optional)',
  'booking.case.symptomsHint': 'Describe any symptoms you are experiencing',
  'booking.case.urgent': 'Is this urgent?',
  'booking.case.urgentSubtitle': 'We will prioritize your request',
  'booking.case.additional': 'Additional notes (optional)',
  'booking.case.additionalHint': 'Any other information you want to share',
  'booking.case.help':
      'Providing details helps the provider prepare for your visit.',
  'booking.case.private': 'Your information is kept confidential',
  'booking.review.title': 'Review booking',
  'booking.review.provider': 'Provider',
  'booking.review.currentCase': 'Current case',
  'booking.review.reason': 'Reason',
  'booking.review.symptoms': 'Symptoms',
  'booking.review.urgency': 'Urgency',
  'booking.review.urgent': 'Urgent',
  'booking.review.routine': 'Routine',
  'booking.review.address': 'Address',
  'booking.review.price': 'Price',
  'booking.review.fees': 'Fees',
  'booking.review.service': 'Service',
  'booking.review.appointmentType': 'Appointment type',
  'booking.review.total': 'Total',
  'booking.review.nextPayment':
      'You will choose cash, card, or wallet on the next step.',
  'booking.review.continuePayment': 'Continue to payment',
  'booking.review.submitFailed':
      'Could not create the booking. Please try again.',
  'app.name': 'CareLink',
  'language.switchToArabic': 'Arabic',
  'language.switchToEnglish': 'English',
  'theme.light': 'Light mode',
  'theme.dark': 'Dark mode',
  'intro.trustPill': 'Trusted. Secure. Smart Care.',
  'intro.headline1': 'Better care,',
  'intro.headline2': 'connected.',
  'intro.subtitle':
      'Get instant AI-powered health insights, book trusted providers, and manage your care journey anywhere.',
  'intro.getStarted': 'Get Started',
  'intro.aiInsights': 'AI Insights',
  'intro.aiInsightsSubtitle': 'Smart health recommendations',
  'intro.findProviders': 'Find Providers',
  'intro.findProvidersSubtitle': 'Book trusted doctors',
  'intro.medications': 'Medications',
  'intro.medicationsSubtitle': 'Manage and order your medicines',
  'intro.healthRecords': 'Health Records',
  'intro.healthRecordsSubtitle': 'Store and access your records',
  'intro.labTests': 'Lab & Tests',
  'intro.labTestsSubtitle': 'Book tests and get reports',
  'intro.consultOnline': 'Consult Online',
  'intro.consultOnlineSubtitle': 'Talk to doctors from anywhere',
  'intro.securePrivate': 'Secure & Private',
  'intro.securePrivateSubtitle': 'Your data is 100% safe',
  'intro.aiPowered': 'AI Powered',
  'intro.aiPoweredSubtitle': 'Smarter health insights',
  'intro.anywhereAccess': 'Anywhere Access',
  'intro.anywhereAccessSubtitle': 'Care at your fingertips',
  'auth.signIn': 'Sign In',
  'auth.loginSubtitle':
      'Access your account to manage your health and appointments.',
  'auth.email': 'Email Address',
  'auth.password': 'Password',
  'auth.rememberMe': 'Remember me',
  'auth.forgotPassword': 'Forgot password?',
  'auth.forgotPasswordTitle': 'Forgot Password',
  'auth.forgotPasswordBody':
      'Enter your email address and we will send you password reset instructions.',
  'auth.cancel': 'Cancel',
  'auth.send': 'Send',
  'auth.orContinueWith': 'or continue with',
  'auth.noAccount': "Don't have an account? ",
  'auth.signUp': 'Sign Up',
  'auth.loginSuccessful': 'Login successful',
  'auth.invalidServerUser': 'Invalid server response: user data not found',
  'auth.enterEmailPassword': 'Please enter email and password',
  'auth.enterValidEmail': 'Please enter a valid email address',
  'auth.enterEmail': 'Please enter your email',
  'auth.resetSent': 'If this email exists, reset instructions have been sent.',
  'auth.doctorNotConnected': 'Doctor dashboard is not connected yet',
  'auth.adminNotConnected': 'Admin dashboard is not connected yet',
  'auth.unknownRole': 'Unknown user role: {role}',
  'auth.microsoftNotConnected':
      'Microsoft sign-in is not connected yet. Use email or Google / Apple.',
  'auth.comingSoon': 'Coming soon',
  'auth.passwordRequired': 'Please enter your password',
  'auth.checkForm': 'Please correct the highlighted fields.',
  'auth.emailNotRegistered': 'Email not registered',
  'auth.checkEmail': 'Check your email for reset instructions.',
  'auth.chooseResetMethod': 'How would you like to reset your password?',
  'auth.resetViaEmail': 'Email',
  'auth.resetViaPhone': 'Phone',
  'auth.phone': 'Phone number',
  'auth.enterPhone': 'Enter your phone number',
  'auth.invalidPhone': 'Enter 8–15 digits only',
  'auth.otpCode': 'Verification code',
  'auth.sendCode': 'Send code',
  'auth.resendIn': 'Resend in {seconds}s',
  'auth.resendCode': 'Resend code',
  'auth.verifyAndContinue': 'Verify code',
  'auth.invalidOtp': 'Invalid or expired code',
  'auth.newPassword': 'New password',
  'auth.confirmNewPassword': 'Confirm new password',
  'auth.resetPassword': 'Update password',
  'auth.phoneNotRegistered': 'Phone not registered',
  'auth.passwordsNoMatch': 'Passwords do not match',
  'auth.verifying': 'Verifying…',
  'auth.devOtpHint': 'Dev OTP: {code}',
  'auth.verificationCodeSentEmail': 'Verification code sent to your email',
  'auth.verificationCodeSentPhone': 'Verification code sent to your phone',
  'auth.invalidVerificationCode': 'Invalid verification code',
  'auth.emailVerifiedSuccess': 'Email verified successfully',
  'auth.phoneVerifiedSuccess': 'Phone verified successfully',
  'auth.enterCodeHint':
      'Enter the 6-digit code we sent. Codes expire in 5 minutes.',
  'auth.forgotPasswordEmailSubtitle':
      'We will send a code to your email to confirm you own this address.',
  'auth.forgotPasswordPhoneSubtitle':
      'We will send a code by SMS (when configured) to confirm you own this number.',
  'auth.verifyEmailFirst':
      'Verify your email with the code sent before signing up.',
  'auth.verifyPhoneFirst':
      'Verify your phone with the code sent before signing up.',
  'auth.chooseAccountType': 'Choose Account Type',
  'auth.patient': 'Patient',
  'auth.patientDesc': 'Manage appointments, health records, and connect with providers.',
  'auth.doctor': 'Doctor',
  'auth.doctorDesc': 'Consult patients, write reports, and manage availability.',
  'auth.nurse': 'Nurse',
  'auth.nurseDesc': 'Provide home care support, coordinate visits, and track services.',
  'auth.personalInfo': 'Account Details',
  'auth.chronicDiseases': 'Chronic conditions (optional)',
  'auth.allergies': 'Allergies (optional)',
  'auth.currentMedications': 'Current medications (optional)',
  'auth.emergencyContact': 'Emergency contact (optional)',
  'auth.specialization': 'Medical Specialty',
  'auth.licenseNumber': 'License number',
  'auth.experienceYears': 'Years of experience',
  'auth.clinicHospitalName': 'Clinic or hospital name (optional)',
  'auth.consultationType': 'Consultation type',
  'auth.homeCareAvailability': 'Available for home care visits',
  'auth.serviceAreas': 'Service areas',
  'auth.bio': 'Biography (optional)',
  'auth.gender': 'Gender',
  'auth.location': 'Location',
  'auth.fullName': 'Full Name',
  'auth.phoneNumber': 'Phone Number',
  'auth.emailAddress': 'Email Address',
  'auth.confirmPassword': 'Confirm Password',
  'auth.dateOfBirth': 'Date of Birth',
  'auth.locationVerifiedSuccess': 'Location verified successfully',
  'auth.placeholder.fullName': 'Julia Marwan',
  'auth.placeholder.phone': '599000000',
  'auth.placeholder.email': 'name@example.com',
  'auth.placeholder.password': 'Enter password',
  'auth.placeholder.confirmPassword': 'Confirm your password',
  'auth.placeholder.dateOfBirth': 'Select date',
  'auth.passwordChecklist.minChars': 'At least 8 characters',
  'auth.passwordChecklist.uppercase': 'One uppercase letter',
  'auth.passwordChecklist.number': 'One number',
  'patient.allProviders': 'All Providers',
  'patient.voiceUnavailable': 'Voice input is not available on this device.',
  'patient.typeCareNeed': 'Type or say what care you need, then tap Find.',
  'patient.providersLoading':
      'Provider list is still loading - try again shortly.',
  'patient.goodMorning': 'Good morning',
  'patient.goodAfternoon': 'Good afternoon',
  'patient.goodEvening': 'Good evening',
  'patient.recommendedForYou': 'Recommended for you',
  'patient.typeOrSpeak':
      'Type or speak your need. For personalized medical fit, add your record under Profile > Medical Records.',
  'patient.recommended': 'Recommended: {provider}',
  'patient.find': 'Find',
  'patient.stopVoice': 'Stop voice input',
  'patient.speakNeed': 'Speak your care need',
  'patient.signInEditProfile': 'Sign in to edit your profile.',
  'patient.hiLoading': 'Hi...',
  'patient.hiName': 'Hi, {name}',
  'patient.bookNextVisit': 'Book your next visit',
  'patient.homeNursingCare': 'Home Nursing Care',
  'patient.trustedCare': 'Trusted care',
  'patient.book': 'Book',
  'patient.navHome': 'Home',
  'patient.navCare': 'My care',
  'patient.navChat': 'Chat',
  'patient.navProfile': 'Profile',
  'patient.listening': 'Listening',
  'patient.listeningRequest': 'Listening to your request',
  'patient.askAi': 'Ask CareLink AI',
  'patient.sayOrType': 'Say or type the care you need to rank providers.',
  'patient.profile': 'Profile',
  'patient.editProfile': 'Edit profile',
  'patient.medicalRecords': 'Medical records',
  'patient.paymentHistory': 'Payment history',
  'patient.notifications': 'Notifications',
  'patient.logout': 'Logout',
  'patient.accountType': 'Account type: {type}',
  'patient.accountDeleteNotice':
      'Disable/Delete account will be added in a secure flow soon.',
  'patient.emailLabel': 'Email',
  'patient.phoneLabel': 'Phone',
  'patient.addressLabel': 'Address',
  'patient.dobLabel': 'Date of birth',
  'patient.genderLabel': 'Gender',
  'patient.noName': 'No name',
  'patient.noEmail': 'No email',
  'notifications.title': 'Notifications',
  'notifications.readAll': 'Read all',
  'notifications.recentTitle': 'Recent',
  'notifications.signInMessage': 'Sign in to load your notifications.',
  'notifications.emptyTitle': 'No notifications yet',
  'notifications.emptySubtitle': 'You will see your updates here.',
  'notifications.offlineFallback':
      'Could not connect to the server. Showing sample notifications.',
  'notifications.justNow': 'Just now',
  'notifications.oneMinuteAgo': '1 min ago',
  'notifications.minutesAgo': '{count} min ago',
  'notifications.oneHourAgo': '1 hr ago',
  'notifications.hoursAgo': '{count} hr ago',
  'notifications.oneDayAgo': '1 day ago',
  'notifications.daysAgo': '{count} days ago',
  'notifications.defaultNotification':
      'You have a new notification for your CareLink account.',
  'notifications.demo.appointmentConfirmed': 'Appointment confirmed',
  'notifications.demo.appointmentConfirmedDescription':
      'Your appointment has been confirmed.',
  'notifications.demo.newMessage': 'New message',
  'notifications.demo.newMessageDescription': 'Doctor sent you a new message.',
  'notifications.demo.medicalRecordUploaded': 'Medical record uploaded',
  'notifications.demo.medicalRecordUploadedDescription':
      'A new file was added to your records.',
  'notifications.demo.appointmentReminder': 'Appointment reminder',
  'notifications.demo.appointmentReminderDescription':
      'Appointment tomorrow at 10:00 AM.',
  'notifications.demo.accountSecurity': 'Account security',
  'notifications.demo.accountSecurityDescription':
      'Your email was used to sign in on a new device.',
  'nurse.title': 'Care Link - Nurse',
  'nurse.dashboard': 'Dashboard',
  'nurse.requests': 'Requests',
  'nurse.reports': 'Reports',
  'nurse.payments': 'Payments',
  'nurse.settings': 'Settings',
  'nurse.welcome': 'Welcome, {name}',
  'nurse.matter': 'Your healthcare services matter',
  'nurse.quickOverview': 'Quick Overview',
  'nurse.pendingRequests': 'Pending Requests',
  'nurse.todaysVisits': "Today's Visits",
  'nurse.completed': 'Completed',
  'nurse.earnings': 'Earnings',
  'nurse.quickActions': 'Quick Actions',
  'nurse.profile': 'Profile',
  'nurse.profileSubtitle': 'Update your professional profile',
  'nurse.serviceRequests': 'Service Requests',
  'nurse.serviceRequestsSubtitle': 'Accept or reject new requests',
  'nurse.submitReport': 'Submit Report',
  'nurse.submitReportSubtitle': 'Document completed visits',
  'nurse.paymentHistory': 'Payment History',
  'nurse.paymentHistorySubtitle': 'View earnings and payments',
  'nurse.settingsSubtitle': 'Manage profile and preferences',
  'schedule.title': 'My Bookings',
  'schedule.tabs.upcoming': 'Upcoming',
  'schedule.tabs.waiting': 'Waiting',
  'schedule.tabs.completed': 'Completed',
  'schedule.tabs.cancelled': 'Cancelled',
  'schedule.viewDetails': 'View Details',
  'schedule.contactProvider': 'Contact Provider',
  'schedule.cancelBooking': 'Cancel Booking',
  'schedule.rateProvider': 'Rate Provider',
  'schedule.payNow': 'Pay Now',
  'schedule.card.specialty': 'Specialty',
  'schedule.card.type': 'Appointment Type',
  'schedule.card.home': 'Home Visit',
  'schedule.card.remote': 'Remote Consultation',
  'schedule.card.paid': 'Total Paid',
  'schedule.card.paymentStatus': 'Payment Status',
  'schedule.card.bookingStatus': 'Booking Status',
  'schedule.card.ref': 'Ref',
  'schedule.cancel.dialogTitle': 'Cancel Booking',
  'schedule.cancel.dialogMsg': 'Are you sure you want to cancel this booking?',
  'schedule.cancel.confirm': 'Yes, Cancel',
  'schedule.cancel.keep': 'No, Keep',
  'schedule.edit': 'Edit Appointment',
  'schedule.bookAgain': 'Book Again',
  'schedule.edit.title': 'Reschedule Appointment',
  'schedule.edit.selectTime': 'Select Available Time',
  'schedule.edit.save': 'Save Changes',
  'schedule.noBookings': 'No bookings found',
  'payment.title': 'Payment',
  'payment.completePayment': 'Complete payment',
  'payment.enterCardInfo':
      'Enter your card details. We only save a masked version.',
  'payment.cardDetails': 'Card Details',
  'payment.cardHolderName': 'Card Holder Name',
  'payment.cardNumber': 'Card Number',
  'payment.expiry': 'Expiry (MM/YY)',
  'payment.cvv': 'CVV',
  'payment.currency': 'ILS',
  'payment.currencySymbol': 'ILS',
  'payment.servicePrice': 'Service price',
  'payment.remoteDiscount': 'Remote discount (30%)',
  'payment.totalAmount': 'Total amount',
  'payment.pay': 'Pay {amount} ILS',
  'payment.processing': 'Processing…',
  'payment.bookingConfirmed': 'Booking confirmed',
  'payment.amountHeld': 'Amount held in system',
  'payment.success': 'Payment recorded',
};

const Map<String, String> _ar = {
  'booking.step.service': 'الخدمة',
  'booking.step.dateTime': 'التاريخ والوقت',
  'booking.step.location': 'الموقع',
  'booking.step.details': 'التفاصيل',
  'booking.step.review': 'المراجعة',
  'booking.selectService.title': 'اختيار الخدمة',
  'booking.selectService.subtitle': 'اختر الرعاية التي تحتاجها',
  'booking.selectService.prompt': 'ما نوع الرعاية التي تحتاجها؟',
  'booking.selectService.promptSubtitle': 'اختر الخدمة ثم مقدم رعاية متاح.',
  'booking.appointmentType': 'نوع الموعد',
  'booking.homeVisit': 'زيارة منزلية',
  'booking.remoteConsultation': 'استشارة عن بعد',
  'booking.chooseProvider': 'اختر مقدم الرعاية',
  'booking.loadingProviders': 'جاري تحميل مقدمي الرعاية...',
  'booking.noProvidersForService': 'لا يوجد مقدمون متاحون لهذه الخدمة حالياً.',
  'booking.providerUnavailable': 'مقدم الرعاية غير متاح حالياً.',
  'booking.continue': 'متابعة',
  'booking.tryAgain': 'إعادة المحاولة',
  'booking.service.homeNursing': 'تمريض منزلي',
  'booking.service.homeNursing.desc': 'رعاية تمريضية متخصصة في منزلك.',
  'booking.service.generalDoctor': 'طبيب عام',
  'booking.service.generalDoctor.desc': 'استشارة طبية وإرشاد صحي عام.',
  'booking.service.postSurgery': 'رعاية بعد العمليات',
  'booking.service.postSurgery.desc': 'متابعة ودعم بعد الإجراءات الطبية.',
  'booking.service.elderlyCare': 'رعاية كبار السن',
  'booking.service.elderlyCare.desc': 'دعم محترم للصحة والراحة اليومية.',
  'booking.service.physiotherapy': 'علاج طبيعي',
  'booking.service.physiotherapy.desc': 'دعم للحركة والتعافي وإعادة التأهيل.',
  'booking.service.mentalSupport': 'دعم نفسي',
  'booking.service.mentalSupport.desc': 'دعم عن بعد للصحة النفسية والراحة.',
  'booking.dateTime.title': 'اختيار التاريخ والوقت',
  'booking.dateTime.subtitle': 'اختر موعد الزيارة',
  'booking.dateTime.prompt': 'اختر التاريخ والوقت المناسبين',
  'booking.dateTime.promptSubtitle':
      'الأوقات المعروضة مأخوذة من توفر مقدم الرعاية.',
  'booking.dateTime.chooseFirst': 'يرجى اختيار التاريخ والوقت أولاً',
  'booking.dateTime.notAvailable': 'مقدم الرعاية غير متاح حالياً.',
  'booking.dateTime.chooseAnotherProvider':
      'يرجى اختيار مقدم رعاية آخر للمتابعة.',
  'booking.dateTime.selectDate': 'اختر التاريخ',
  'booking.dateTime.selectTime': 'اختر الوقت',
  'booking.dateTime.noTimes': 'لا توجد أوقات متاحة لهذا التاريخ.',
  'booking.dateTime.approx': 'جميع الأوقات تقريبية وقد تتغير.',
  'booking.dateTime.monthHelp': 'اختر الشهر والسنة',
  'booking.location.title': 'اختر العنوان',
  'booking.location.chooseAddress': 'اختر العنوان',
  'booking.location.useThisAddress': 'استخدام هذا العنوان',
  'booking.location.subtitle': 'حدد مكان زيارة مقدم الرعاية',
  'booking.location.confirm': 'تأكيد الموقع',
  'booking.location.useCurrent': 'استخدام موقعي الحالي',
  'booking.location.adjust': 'حرّك الخريطة لتعديل الموقع',
  'booking.location.address': 'العنوان',
  'booking.location.addressHint': 'اكتب المدينة أو المكان واختر النتيجة',
  'booking.location.note': 'ملاحظة الموقع (اختياري)',
  'booking.location.noteHint': 'الشقة أو الطابق أو المدخل أو معلم قريب',
  'booking.location.private': 'يُستخدم موقعك لهذا الحجز فقط',
  'booking.case.title': 'تفاصيل الحالة',
  'booking.case.subtitle': 'أخبرنا بما تحتاجه لهذه الزيارة',
  'booking.case.prompt': 'الحالة الحالية',
  'booking.case.promptSubtitle':
      'تساعد هذه المعلومات مقدم الرعاية على الاستعداد للحجز.',
  'booking.case.reason': 'سبب الزيارة',
  'booking.case.reasonHint': 'يرجى وصف سبب الزيارة',
  'booking.case.symptoms': 'الأعراض (اختياري)',
  'booking.case.symptomsHint': 'صف أي أعراض تشعر بها',
  'booking.case.urgent': 'هل الحالة عاجلة؟',
  'booking.case.urgentSubtitle': 'سنمنح طلبك أولوية',
  'booking.case.additional': 'ملاحظات إضافية (اختياري)',
  'booking.case.additionalHint': 'أي معلومات أخرى ترغب بمشاركتها',
  'booking.case.help': 'تساعد التفاصيل مقدم الرعاية على الاستعداد لزيارتك.',
  'booking.case.private': 'معلوماتك محفوظة بسرية',
  'booking.review.title': 'مراجعة الحجز',
  'booking.review.provider': 'مقدم الرعاية',
  'booking.review.currentCase': 'الحالة الحالية',
  'booking.review.reason': 'السبب',
  'booking.review.symptoms': 'الأعراض',
  'booking.review.urgency': 'درجة الاستعجال',
  'booking.review.urgent': 'عاجلة',
  'booking.review.routine': 'عادية',
  'booking.review.address': 'العنوان',
  'booking.review.price': 'السعر',
  'booking.review.fees': 'الرسوم',
  'booking.review.service': 'الخدمة',
  'booking.review.appointmentType': 'نوع الموعد',
  'booking.review.total': 'الإجمالي',
  'booking.review.nextPayment':
      'ستختار الدفع نقداً أو بالبطاقة أو بالمحفظة في الخطوة التالية.',
  'booking.review.continuePayment': 'المتابعة إلى الدفع',
  'booking.review.submitFailed': 'تعذر إنشاء الحجز. حاول مرة أخرى.',
  'app.name': 'كيرلينك',
  'language.switchToArabic': 'العربية',
  'language.switchToEnglish': 'English',
  'theme.light': 'وضع فاتح',
  'theme.dark': 'وضع داكن',
  'intro.trustPill': 'موثوق. آمن. رعاية ذكية.',
  'intro.headline1': 'رعاية أفضل،',
  'intro.headline2': 'بترابط أسهل.',
  'intro.subtitle':
      'احصل على توصيات صحية ذكية، واحجز مزودي رعاية موثوقين، وأدر رحلتك الصحية من أي مكان.',
  'intro.getStarted': 'ابدأ الآن',
  'intro.aiInsights': 'رؤى ذكية',
  'intro.aiInsightsSubtitle': 'توصيات صحية ذكية',
  'intro.findProviders': 'ابحث عن مزودين',
  'intro.findProvidersSubtitle': 'احجز أطباء موثوقين',
  'intro.medications': 'الأدوية',
  'intro.medicationsSubtitle': 'إدارة وطلب الأدوية',
  'intro.healthRecords': 'السجلات الصحية',
  'intro.healthRecordsSubtitle': 'احفظ سجلاتك وادخل إليها',
  'intro.labTests': 'المختبر والفحوصات',
  'intro.labTestsSubtitle': 'احجز فحوصات واستلم التقارير',
  'intro.consultOnline': 'استشارة أونلاين',
  'intro.consultOnlineSubtitle': 'تواصل مع الأطباء من أي مكان',
  'intro.securePrivate': 'آمن وخاص',
  'intro.securePrivateSubtitle': 'بياناتك آمنة 100%',
  'intro.aiPowered': 'مدعوم بالذكاء',
  'intro.aiPoweredSubtitle': 'رؤى صحية أذكى',
  'intro.anywhereAccess': 'وصول من أي مكان',
  'intro.anywhereAccessSubtitle': 'الرعاية بين يديك',
  'auth.signIn': 'تسجيل الدخول',
  'auth.loginSubtitle': 'ادخل إلى حسابك لإدارة صحتك ومواعيدك.',
  'auth.email': 'البريد الإلكتروني',
  'auth.password': 'كلمة المرور',
  'auth.rememberMe': 'تذكرني',
  'auth.forgotPassword': 'نسيت كلمة المرور؟',
  'auth.forgotPasswordTitle': 'استعادة كلمة المرور',
  'auth.forgotPasswordBody':
      'أدخل بريدك الإلكتروني وسنرسل لك تعليمات إعادة تعيين كلمة المرور.',
  'auth.cancel': 'إلغاء',
  'auth.send': 'إرسال',
  'auth.orContinueWith': 'أو تابع باستخدام',
  'auth.noAccount': 'ليس لديك حساب؟ ',
  'auth.signUp': 'إنشاء حساب',
  'auth.loginSuccessful': 'تم تسجيل الدخول بنجاح',
  'auth.invalidServerUser':
      'استجابة الخادم غير صحيحة: بيانات المستخدم غير موجودة',
  'auth.enterEmailPassword': 'يرجى إدخال البريد الإلكتروني وكلمة المرور',
  'auth.enterValidEmail': 'يرجى إدخال بريد إلكتروني صحيح',
  'auth.enterEmail': 'يرجى إدخال بريدك الإلكتروني',
  'auth.resetSent':
      'إذا كان هذا البريد موجوداً، تم إرسال تعليمات إعادة التعيين.',
  'auth.doctorNotConnected': 'لوحة الطبيب غير مربوطة بعد',
  'auth.adminNotConnected': 'لوحة المدير غير مربوطة بعد',
  'auth.unknownRole': 'نوع المستخدم غير معروف: {role}',
  'auth.microsoftNotConnected':
      'تسجيل الدخول عبر Microsoft غير مربوط بعد. استخدم البريد أو Google / Apple.',
  'auth.comingSoon': 'قريباً',
  'auth.passwordRequired': 'يرجى إدخال كلمة المرور',
  'auth.checkForm': 'يرجى تصحيح الحقول المظللة.',
  'auth.emailNotRegistered': 'البريد الإلكتروني غير مسجل',
  'auth.checkEmail': 'تحقق من بريدك الإلكتروني لتعليمات إعادة التعيين.',
  'auth.chooseResetMethod': 'كيف تريد إعادة تعيين كلمة المرور؟',
  'auth.resetViaEmail': 'البريد الإلكتروني',
  'auth.resetViaPhone': 'الهاتف',
  'auth.phone': 'رقم الهاتف',
  'auth.enterPhone': 'أدخل رقم هاتفك',
  'auth.invalidPhone': 'أدخل 8–15 رقماً فقط',
  'auth.otpCode': 'رمز التحقق',
  'auth.sendCode': 'إرسال الرمز',
  'auth.resendIn': 'أعد الإرسال خلال {seconds} ث',
  'auth.resendCode': 'إعادة إرسال الرمز',
  'auth.verifyAndContinue': 'تحقق من الرمز',
  'auth.invalidOtp': 'رمز غير صحيح أو منتهي',
  'auth.newPassword': 'كلمة المرور الجديدة',
  'auth.confirmNewPassword': 'تأكيد كلمة المرور',
  'auth.resetPassword': 'تحديث كلمة المرور',
  'auth.phoneNotRegistered': 'رقم الهاتف غير مسجل',
  'auth.passwordsNoMatch': 'كلمتا المرور غير متطابقتين',
  'auth.verifying': 'جاري التحقق…',
  'auth.devOtpHint': 'رمز التجربة: {code}',
  'auth.verificationCodeSentEmail': 'تم إرسال رمز التحقق إلى بريدك',
  'auth.verificationCodeSentPhone': 'تم إرسال رمز التحقق إلى هاتفك',
  'auth.invalidVerificationCode': 'رمز التحقق غير صحيح',
  'auth.emailVerifiedSuccess': 'تم التحقق من البريد الإلكتروني بنجاح',
  'auth.phoneVerifiedSuccess': 'تم التحقق من الهاتف بنجاح',
  'auth.enterCodeHint': 'أدخل الرمز المكوّن من 6 أرقام. ينتهي خلال 5 دقائق.',
  'auth.forgotPasswordEmailSubtitle':
      'سنرسل رمزاً إلى بريدك لتأكيد أنك تملك هذا العنوان.',
  'auth.forgotPasswordPhoneSubtitle':
      'سنرسل رمزاً عبر الرسائل (عند التفعيل) لتأكيد رقمك.',
  'auth.verifyEmailFirst': 'تحقق من بريدك بالرمز المرسل قبل إنشاء الحساب.',
  'auth.verifyPhoneFirst': 'تحقق من هاتفك بالرمز المرسل قبل إنشاء الحساب.',
  'auth.chooseAccountType': 'اختر نوع الحساب',
  'auth.patient': 'مريض',
  'auth.patientDesc': 'إدارة المواعيد، السجلات الصحية، والتواصل مع مقدمي الخدمة.',
  'auth.doctor': 'طبيب',
  'auth.doctorDesc': 'تقديم الاستشارات للمرضى، كتابة التقارير، وإدارة التوفر.',
  'auth.nurse': 'ممرض/ممرضة',
  'auth.nurseDesc': 'تقديم خدمات التمريض المنزلي، تنسيق الزيارات، ومتابعة الأداء.',
  'auth.personalInfo': 'تفاصيل الحساب',
  'auth.chronicDiseases': 'الأمراض المزمنة (اختياري)',
  'auth.allergies': 'الحساسية (اختياري)',
  'auth.currentMedications': 'الأدوية الحالية (اختياري)',
  'auth.emergencyContact': 'جهة اتصال الطوارئ (اختياري)',
  'auth.specialization': 'التخصص الطبي',
  'auth.licenseNumber': 'رقم الترخيص',
  'auth.experienceYears': 'سنوات الخبرة',
  'auth.clinicHospitalName': 'اسم العيادة أو المستشفى (اختياري)',
  'auth.consultationType': 'نوع الاستشارة',
  'auth.homeCareAvailability': 'متاح لزيارات الرعاية المنزلية',
  'auth.serviceAreas': 'مناطق الخدمة',
  'auth.bio': 'نبذة تعريفية (اختياري)',
  'auth.gender': 'الجنس',
  'auth.location': 'الموقع الجغرافي',
  'auth.fullName': 'الاسم الكامل',
  'auth.phoneNumber': 'رقم الهاتف',
  'auth.emailAddress': 'البريد الإلكتروني',
  'auth.confirmPassword': 'تأكيد كلمة المرور',
  'auth.dateOfBirth': 'تاريخ الميلاد',
  'auth.locationVerifiedSuccess': 'تم التحقق من الموقع بنجاح',
  'auth.placeholder.fullName': 'جوليا مروان',
  'auth.placeholder.phone': '599000000',
  'auth.placeholder.email': 'name@example.com',
  'auth.placeholder.password': 'أدخل كلمة المرور',
  'auth.placeholder.confirmPassword': 'تأكيد كلمة المرور الخاصة بك',
  'auth.placeholder.dateOfBirth': 'اختر التاريخ',
  'auth.passwordChecklist.minChars': '8 أحرف على الأقل',
  'auth.passwordChecklist.uppercase': 'حرف كبير واحد',
  'auth.passwordChecklist.number': 'رقم واحد',
  'patient.allProviders': 'كل مزودي الرعاية',
  'patient.voiceUnavailable': 'الإدخال الصوتي غير متاح على هذا الجهاز.',
  'patient.typeCareNeed': 'اكتب أو قل نوع الرعاية التي تحتاجها، ثم اضغط بحث.',
  'patient.providersLoading': 'قائمة المزودين ما زالت تتحمل - حاول بعد قليل.',
  'patient.goodMorning': 'صباح الخير',
  'patient.goodAfternoon': 'مساء الخير',
  'patient.goodEvening': 'مساء الخير',
  'patient.recommendedForYou': 'موصى به لك',
  'patient.typeOrSpeak':
      'اكتب أو تحدث عن حاجتك. لتوصية أدق، أضف سجلك الطبي من الملف الشخصي > السجلات الطبية.',
  'patient.recommended': 'موصى به: {provider}',
  'patient.find': 'بحث',
  'patient.stopVoice': 'إيقاف الإدخال الصوتي',
  'patient.speakNeed': 'تحدث عن الرعاية التي تحتاجها',
  'patient.signInEditProfile': 'سجل الدخول لتعديل ملفك الشخصي.',
  'patient.hiLoading': 'أهلاً...',
  'patient.hiName': 'أهلاً، {name}',
  'patient.bookNextVisit': 'احجز زيارتك القادمة',
  'patient.homeNursingCare': 'رعاية تمريض منزلية',
  'patient.trustedCare': 'رعاية موثوقة',
  'patient.book': 'حجز',
  'patient.navHome': 'الرئيسية',
  'patient.navCare': 'رعايتي',
  'patient.navChat': 'الدردشة',
  'patient.navProfile': 'الملف',
  'patient.listening': 'أستمع',
  'patient.listeningRequest': 'أستمع إلى طلبك',
  'patient.askAi': 'اسأل ذكاء CareLink',
  'patient.sayOrType': 'قل أو اكتب نوع الرعاية لترتيب المزودين.',
  'patient.profile': 'الملف الشخصي',
  'patient.editProfile': 'تعديل الملف الشخصي',
  'patient.medicalRecords': 'السجلات الطبية',
  'patient.paymentHistory': 'سجل المدفوعات',
  'patient.notifications': 'الإشعارات',
  'patient.logout': 'تسجيل الخروج',
  'patient.accountType': 'نوع الحساب: {type}',
  'patient.accountDeleteNotice':
      'سيتم إضافة خيار تعطيل/حذف الحساب في مسار آمن قريبًا.',
  'patient.emailLabel': 'البريد الإلكتروني',
  'patient.phoneLabel': 'الهاتف',
  'patient.addressLabel': 'العنوان',
  'patient.dobLabel': 'تاريخ الميلاد',
  'patient.genderLabel': 'الجنس',
  'patient.noName': 'لا يوجد اسم',
  'patient.noEmail': 'لا يوجد بريد إلكتروني',
  'notifications.title': 'الإشعارات',
  'notifications.readAll': 'تعيين الكل مقروء',
  'notifications.recentTitle': 'الأحدث',
  'notifications.signInMessage': 'سجّل دخولك لتحميل إشعاراتك.',
  'notifications.emptyTitle': 'لا توجد إشعارات بعد',
  'notifications.emptySubtitle': 'ستظهر تحديثاتك هنا.',
  'notifications.offlineFallback': 'تعذر الاتصال بالخادم. عرض إشعارات تجريبية.',
  'notifications.justNow': 'الآن',
  'notifications.oneMinuteAgo': 'قبل دقيقة',
  'notifications.minutesAgo': 'قبل {count} دقيقة',
  'notifications.oneHourAgo': 'قبل ساعة',
  'notifications.hoursAgo': 'قبل {count} ساعة',
  'notifications.oneDayAgo': 'قبل يوم',
  'notifications.daysAgo': 'قبل {count} أيام',
  'notifications.defaultNotification':
      'لديك إشعار جديد لحساب CareLink الخاص بك.',
  'notifications.demo.appointmentConfirmed': 'تم تأكيد الموعد',
  'notifications.demo.appointmentConfirmedDescription': 'تم تأكيد موعدك.',
  'notifications.demo.newMessage': 'رسالة جديدة',
  'notifications.demo.newMessageDescription': 'أرسل لك الطبيب رسالة جديدة.',
  'notifications.demo.medicalRecordUploaded': 'تم تحميل سجل طبي',
  'notifications.demo.medicalRecordUploadedDescription':
      'تمت إضافة ملف جديد إلى سجلاتك.',
  'notifications.demo.appointmentReminder': 'تذكير بالموعد',
  'notifications.demo.appointmentReminderDescription':
      'الموعد غداً الساعة 10:00 صباحاً.',
  'notifications.demo.accountSecurity': 'أمن الحساب',
  'notifications.demo.accountSecurityDescription':
      'تم استخدام بريدك الإلكتروني لتسجيل الدخول على جهاز جديد.',
  'nurse.title': 'كيرلينك - الممرض',
  'nurse.dashboard': 'اللوحة',
  'nurse.requests': 'الطلبات',
  'nurse.reports': 'التقارير',
  'nurse.payments': 'المدفوعات',
  'nurse.settings': 'الإعدادات',
  'nurse.welcome': 'أهلاً، {name}',
  'nurse.matter': 'خدماتك الصحية تصنع فرقاً',
  'nurse.quickOverview': 'نظرة سريعة',
  'nurse.pendingRequests': 'طلبات قيد الانتظار',
  'nurse.todaysVisits': 'زيارات اليوم',
  'nurse.completed': 'مكتملة',
  'nurse.earnings': 'الأرباح',
  'nurse.quickActions': 'إجراءات سريعة',
  'nurse.profile': 'الملف المهني',
  'nurse.profileSubtitle': 'حدّث ملفك المهني',
  'nurse.serviceRequests': 'طلبات الخدمة',
  'nurse.serviceRequestsSubtitle': 'اقبل أو ارفض الطلبات الجديدة',
  'nurse.submitReport': 'إرسال تقرير',
  'nurse.submitReportSubtitle': 'وثّق الزيارات المكتملة',
  'nurse.paymentHistory': 'سجل المدفوعات',
  'nurse.paymentHistorySubtitle': 'راجع الأرباح والمدفوعات',
  'nurse.settingsSubtitle': 'إدارة الملف والتفضيلات',
  'schedule.title': 'حجوزاتي',
  'schedule.tabs.upcoming': 'القادمة',
  'schedule.tabs.waiting': 'بانتظار الرد',
  'schedule.tabs.completed': 'المكتملة',
  'schedule.tabs.cancelled': 'الملغاة',
  'schedule.viewDetails': 'عرض التفاصيل',
  'schedule.contactProvider': 'تواصل مع مقدم الرعاية',
  'schedule.cancelBooking': 'إلغاء الحجز',
  'schedule.rateProvider': 'تقييم مقدم الرعاية',
  'schedule.payNow': 'ادفع الآن',
  'schedule.card.specialty': 'التخصص',
  'schedule.card.type': 'نوع الموعد',
  'schedule.card.home': 'زيارة منزلية',
  'schedule.card.remote': 'استشارة عن بعد',
  'schedule.card.paid': 'إجمالي المدفوع',
  'schedule.card.paymentStatus': 'حالة الدفع',
  'schedule.card.bookingStatus': 'حالة الحجز',
  'schedule.card.ref': 'مرجع',
  'schedule.cancel.dialogTitle': 'إلغاء الحجز',
  'schedule.cancel.dialogMsg': 'هل أنت متأكد من أنك تريد إلغاء هذا الحجز؟',
  'schedule.cancel.confirm': 'نعم، إلغاء',
  'schedule.cancel.keep': 'لا، إبقاء',
  'schedule.edit': 'تعديل الموعد',
  'schedule.bookAgain': 'احجز مرة أخرى',
  'schedule.edit.title': 'إعادة جدولة الموعد',
  'schedule.edit.selectTime': 'اختر موعداً متاحاً',
  'schedule.edit.save': 'حفظ التغييرات',
  'schedule.noBookings': 'لا توجد حجوزات',
  'payment.title': 'الدفع',
  'payment.completePayment': 'إتمام الدفع',
  'payment.enterCardInfo':
      'أدخل بيانات بطاقتك. سنحفظ فقط نسخة مخفية منها.',
  'payment.cardDetails': 'بيانات البطاقة',
  'payment.cardHolderName': 'اسم حامل البطاقة',
  'payment.cardNumber': 'رقم البطاقة',
  'payment.expiry': 'تاريخ الانتهاء (MM/YY)',
  'payment.cvv': 'CVV',
  'payment.currency': 'شيكل',
  'payment.currencySymbol': 'ILS',
  'payment.servicePrice': 'سعر الخدمة',
  'payment.remoteDiscount': 'خصم الاستشارة البعيدة (30%)',
  'payment.totalAmount': 'المبلغ الإجمالي',
  'payment.pay': 'ادفع {amount} شيكل',
  'payment.processing': 'جاري المعالجة…',
  'payment.bookingConfirmed': 'تم تأكيد الحجز',
  'payment.amountHeld': 'المبلغ محفوظ في النظام',
  'payment.success': 'تم تسجيل الدفع',
};
