import 'package:flutter/widgets.dart';

class CarelinkL10n {
  const CarelinkL10n(this.locale);

  final Locale locale;

  bool get isArabic => locale.languageCode == 'ar';

  static CarelinkL10n of(BuildContext context) {
    return CarelinkL10n(Localizations.localeOf(context));
  }

  String t(String key, {Map<String, String>? args}) {
    var value = (isArabic ? _ar : _en)[key] ?? _en[key] ?? key;
    if (args != null) {
      for (final entry in args.entries) {
        value = value.replaceAll('{${entry.key}}', entry.value);
      }
    }
    return value;
  }
}

extension CarelinkL10nX on BuildContext {
  CarelinkL10n get l10n => CarelinkL10n.of(this);

  String tr(String key, {Map<String, String>? args}) {
    return l10n.t(key, args: args);
  }
}

const Map<String, String> _en = {
  'app.name': 'CareLink',
  'language.switchToArabic': 'Arabic',
  'language.switchToEnglish': 'English',
  'theme.light': 'Light mode',
  'theme.dark': 'Dark mode',
  'intro.trustPill': 'Trusted. Secure. Smart Care.',
  'intro.headline1': 'Better care,',
  'intro.headline2': 'connected.',
  'intro.subtitle':
      'Get instant AI-powered health insights, book trusted providers, and manage your care journey anywhere.',
  'intro.getStarted': 'Get Started',
  'intro.aiInsights': 'AI Insights',
  'intro.aiInsightsSubtitle': 'Smart health recommendations',
  'intro.findProviders': 'Find Providers',
  'intro.findProvidersSubtitle': 'Book trusted doctors',
  'intro.medications': 'Medications',
  'intro.medicationsSubtitle': 'Manage and order your medicines',
  'intro.healthRecords': 'Health Records',
  'intro.healthRecordsSubtitle': 'Store and access your records',
  'intro.labTests': 'Lab & Tests',
  'intro.labTestsSubtitle': 'Book tests and get reports',
  'intro.consultOnline': 'Consult Online',
  'intro.consultOnlineSubtitle': 'Talk to doctors from anywhere',
  'intro.securePrivate': 'Secure & Private',
  'intro.securePrivateSubtitle': 'Your data is 100% safe',
  'intro.aiPowered': 'AI Powered',
  'intro.aiPoweredSubtitle': 'Smarter health insights',
  'intro.anywhereAccess': 'Anywhere Access',
  'intro.anywhereAccessSubtitle': 'Care at your fingertips',
  'auth.signIn': 'Sign In',
  'auth.loginSubtitle':
      'Access your account to manage your health and appointments.',
  'auth.email': 'Email Address',
  'auth.password': 'Password',
  'auth.rememberMe': 'Remember me',
  'auth.forgotPassword': 'Forgot password?',
  'auth.forgotPasswordTitle': 'Forgot Password',
  'auth.forgotPasswordBody':
      'Enter your email address and we will send you password reset instructions.',
  'auth.cancel': 'Cancel',
  'auth.send': 'Send',
  'auth.orContinueWith': 'or continue with',
  'auth.noAccount': "Don't have an account? ",
  'auth.signUp': 'Sign Up',
  'auth.loginSuccessful': 'Login successful',
  'auth.invalidServerUser': 'Invalid server response: user data not found',
  'auth.enterEmailPassword': 'Please enter email and password',
  'auth.enterValidEmail': 'Please enter a valid email address',
  'auth.enterEmail': 'Please enter your email',
  'auth.resetSent': 'If this email exists, reset instructions have been sent.',
  'auth.doctorNotConnected': 'Doctor dashboard is not connected yet',
  'auth.adminNotConnected': 'Admin dashboard is not connected yet',
  'auth.unknownRole': 'Unknown user role: {role}',
  'auth.microsoftNotConnected':
      'Microsoft sign-in is not connected yet. Use email or Google / Apple.',
  'auth.comingSoon': 'Coming soon',
  'auth.passwordRequired': 'Please enter your password',
  'auth.checkForm': 'Please correct the highlighted fields.',
  'auth.emailNotRegistered': 'Email not registered',
  'auth.checkEmail': 'Check your email for reset instructions.',
  'auth.chooseResetMethod': 'How would you like to reset your password?',
  'auth.resetViaEmail': 'Email',
  'auth.resetViaPhone': 'Phone',
  'auth.phone': 'Phone number',
  'auth.enterPhone': 'Enter your phone number',
  'auth.invalidPhone': 'Enter 8–15 digits only',
  'auth.otpCode': 'Verification code',
  'auth.sendCode': 'Send code',
  'auth.resendIn': 'Resend in {seconds}s',
  'auth.resendCode': 'Resend code',
  'auth.verifyAndContinue': 'Verify code',
  'auth.invalidOtp': 'Invalid or expired code',
  'auth.newPassword': 'New password',
  'auth.confirmNewPassword': 'Confirm new password',
  'auth.resetPassword': 'Update password',
  'auth.phoneNotRegistered': 'Phone not registered',
  'auth.passwordsNoMatch': 'Passwords do not match',
  'auth.verifying': 'Verifying…',
  'auth.devOtpHint': 'Dev OTP: {code}',
  'auth.verificationCodeSentEmail':
      'Verification code sent to your email',
  'auth.verificationCodeSentPhone':
      'Verification code sent to your phone',
  'auth.invalidVerificationCode': 'Invalid verification code',
  'auth.emailVerifiedSuccess': 'Email verified successfully',
  'auth.phoneVerifiedSuccess': 'Phone verified successfully',
  'auth.enterCodeHint':
      'Enter the 6-digit code we sent. Codes expire in 5 minutes.',
  'auth.forgotPasswordEmailSubtitle':
      'We will send a code to your email to confirm you own this address.',
  'auth.forgotPasswordPhoneSubtitle':
      'We will send a code by SMS (when configured) to confirm you own this number.',
  'auth.verifyEmailFirst': 'Verify your email with the code sent before signing up.',
  'auth.verifyPhoneFirst': 'Verify your phone with the code sent before signing up.',
  'patient.allProviders': 'All Providers',
  'patient.voiceUnavailable': 'Voice input is not available on this device.',
  'patient.typeCareNeed': 'Type or say what care you need, then tap Find.',
  'patient.providersLoading':
      'Provider list is still loading - try again shortly.',
  'patient.goodMorning': 'Good morning',
  'patient.goodAfternoon': 'Good afternoon',
  'patient.goodEvening': 'Good evening',
  'patient.recommendedForYou': 'Recommended for you',
  'patient.typeOrSpeak':
      'Type or speak your need. For personalized medical fit, add your record under Profile > Medical Records.',
  'patient.recommended': 'Recommended: {provider}',
  'patient.find': 'Find',
  'patient.stopVoice': 'Stop voice input',
  'patient.speakNeed': 'Speak your care need',
  'patient.signInEditProfile': 'Sign in to edit your profile.',
  'patient.hiLoading': 'Hi...',
  'patient.hiName': 'Hi, {name}',
  'patient.bookNextVisit': 'Book your next visit',
  'patient.homeNursingCare': 'Home Nursing Care',
  'patient.trustedCare': 'Trusted care',
  'patient.book': 'Book',
  'patient.navHome': 'Home',
  'patient.navCare': 'My care',
  'patient.navChat': 'Chat',
  'patient.navProfile': 'Profile',
  'patient.listening': 'Listening',
  'patient.listeningRequest': 'Listening to your request',
  'patient.askAi': 'Ask CareLink AI',
  'patient.sayOrType': 'Say or type the care you need to rank providers.',
  'nurse.title': 'Care Link - Nurse',
  'nurse.dashboard': 'Dashboard',
  'nurse.requests': 'Requests',
  'nurse.reports': 'Reports',
  'nurse.payments': 'Payments',
  'nurse.settings': 'Settings',
  'nurse.welcome': 'Welcome, {name}',
  'nurse.matter': 'Your healthcare services matter',
  'nurse.quickOverview': 'Quick Overview',
  'nurse.pendingRequests': 'Pending Requests',
  'nurse.todaysVisits': "Today's Visits",
  'nurse.completed': 'Completed',
  'nurse.earnings': 'Earnings',
  'nurse.quickActions': 'Quick Actions',
  'nurse.profile': 'Profile',
  'nurse.profileSubtitle': 'Update your professional profile',
  'nurse.serviceRequests': 'Service Requests',
  'nurse.serviceRequestsSubtitle': 'Accept or reject new requests',
  'nurse.submitReport': 'Submit Report',
  'nurse.submitReportSubtitle': 'Document completed visits',
  'nurse.paymentHistory': 'Payment History',
  'nurse.paymentHistorySubtitle': 'View earnings and payments',
  'nurse.settingsSubtitle': 'Manage profile and preferences',
};

const Map<String, String> _ar = {
  'app.name': 'كيرلينك',
  'language.switchToArabic': 'العربية',
  'language.switchToEnglish': 'English',
  'theme.light': 'وضع فاتح',
  'theme.dark': 'وضع داكن',
  'intro.trustPill': 'موثوق. آمن. رعاية ذكية.',
  'intro.headline1': 'رعاية أفضل،',
  'intro.headline2': 'بترابط أسهل.',
  'intro.subtitle':
      'احصل على توصيات صحية ذكية، واحجز مزودي رعاية موثوقين، وأدر رحلتك الصحية من أي مكان.',
  'intro.getStarted': 'ابدأ الآن',
  'intro.aiInsights': 'رؤى ذكية',
  'intro.aiInsightsSubtitle': 'توصيات صحية ذكية',
  'intro.findProviders': 'ابحث عن مزودين',
  'intro.findProvidersSubtitle': 'احجز أطباء موثوقين',
  'intro.medications': 'الأدوية',
  'intro.medicationsSubtitle': 'إدارة وطلب الأدوية',
  'intro.healthRecords': 'السجلات الصحية',
  'intro.healthRecordsSubtitle': 'احفظ سجلاتك وادخل إليها',
  'intro.labTests': 'المختبر والفحوصات',
  'intro.labTestsSubtitle': 'احجز فحوصات واستلم التقارير',
  'intro.consultOnline': 'استشارة أونلاين',
  'intro.consultOnlineSubtitle': 'تواصل مع الأطباء من أي مكان',
  'intro.securePrivate': 'آمن وخاص',
  'intro.securePrivateSubtitle': 'بياناتك آمنة 100%',
  'intro.aiPowered': 'مدعوم بالذكاء',
  'intro.aiPoweredSubtitle': 'رؤى صحية أذكى',
  'intro.anywhereAccess': 'وصول من أي مكان',
  'intro.anywhereAccessSubtitle': 'الرعاية بين يديك',
  'auth.signIn': 'تسجيل الدخول',
  'auth.loginSubtitle': 'ادخل إلى حسابك لإدارة صحتك ومواعيدك.',
  'auth.email': 'البريد الإلكتروني',
  'auth.password': 'كلمة المرور',
  'auth.rememberMe': 'تذكرني',
  'auth.forgotPassword': 'نسيت كلمة المرور؟',
  'auth.forgotPasswordTitle': 'استعادة كلمة المرور',
  'auth.forgotPasswordBody':
      'أدخل بريدك الإلكتروني وسنرسل لك تعليمات إعادة تعيين كلمة المرور.',
  'auth.cancel': 'إلغاء',
  'auth.send': 'إرسال',
  'auth.orContinueWith': 'أو تابع باستخدام',
  'auth.noAccount': 'ليس لديك حساب؟ ',
  'auth.signUp': 'إنشاء حساب',
  'auth.loginSuccessful': 'تم تسجيل الدخول بنجاح',
  'auth.invalidServerUser':
      'استجابة الخادم غير صحيحة: بيانات المستخدم غير موجودة',
  'auth.enterEmailPassword': 'يرجى إدخال البريد الإلكتروني وكلمة المرور',
  'auth.enterValidEmail': 'يرجى إدخال بريد إلكتروني صحيح',
  'auth.enterEmail': 'يرجى إدخال بريدك الإلكتروني',
  'auth.resetSent':
      'إذا كان هذا البريد موجوداً، تم إرسال تعليمات إعادة التعيين.',
  'auth.doctorNotConnected': 'لوحة الطبيب غير مربوطة بعد',
  'auth.adminNotConnected': 'لوحة المدير غير مربوطة بعد',
  'auth.unknownRole': 'نوع المستخدم غير معروف: {role}',
  'auth.microsoftNotConnected':
      'تسجيل الدخول عبر Microsoft غير مربوط بعد. استخدم البريد أو Google / Apple.',
  'auth.comingSoon': 'قريباً',
  'auth.passwordRequired': 'يرجى إدخال كلمة المرور',
  'auth.checkForm': 'يرجى تصحيح الحقول المظللة.',
  'auth.emailNotRegistered': 'البريد الإلكتروني غير مسجل',
  'auth.checkEmail': 'تحقق من بريدك الإلكتروني لتعليمات إعادة التعيين.',
  'auth.chooseResetMethod': 'كيف تريد إعادة تعيين كلمة المرور؟',
  'auth.resetViaEmail': 'البريد الإلكتروني',
  'auth.resetViaPhone': 'الهاتف',
  'auth.phone': 'رقم الهاتف',
  'auth.enterPhone': 'أدخل رقم هاتفك',
  'auth.invalidPhone': 'أدخل 8–15 رقماً فقط',
  'auth.otpCode': 'رمز التحقق',
  'auth.sendCode': 'إرسال الرمز',
  'auth.resendIn': 'أعد الإرسال خلال {seconds} ث',
  'auth.resendCode': 'إعادة إرسال الرمز',
  'auth.verifyAndContinue': 'تحقق من الرمز',
  'auth.invalidOtp': 'رمز غير صحيح أو منتهي',
  'auth.newPassword': 'كلمة المرور الجديدة',
  'auth.confirmNewPassword': 'تأكيد كلمة المرور',
  'auth.resetPassword': 'تحديث كلمة المرور',
  'auth.phoneNotRegistered': 'رقم الهاتف غير مسجل',
  'auth.passwordsNoMatch': 'كلمتا المرور غير متطابقتين',
  'auth.verifying': 'جاري التحقق…',
  'auth.devOtpHint': 'رمز التجربة: {code}',
  'auth.verificationCodeSentEmail': 'تم إرسال رمز التحقق إلى بريدك',
  'auth.verificationCodeSentPhone': 'تم إرسال رمز التحقق إلى هاتفك',
  'auth.invalidVerificationCode': 'رمز التحقق غير صحيح',
  'auth.emailVerifiedSuccess': 'تم التحقق من البريد الإلكتروني بنجاح',
  'auth.phoneVerifiedSuccess': 'تم التحقق من الهاتف بنجاح',
  'auth.enterCodeHint':
      'أدخل الرمز المكوّن من 6 أرقام. ينتهي خلال 5 دقائق.',
  'auth.forgotPasswordEmailSubtitle':
      'سنرسل رمزاً إلى بريدك لتأكيد أنك تملك هذا العنوان.',
  'auth.forgotPasswordPhoneSubtitle':
      'سنرسل رمزاً عبر الرسائل (عند التفعيل) لتأكيد رقمك.',
  'auth.verifyEmailFirst': 'تحقق من بريدك بالرمز المرسل قبل إنشاء الحساب.',
  'auth.verifyPhoneFirst': 'تحقق من هاتفك بالرمز المرسل قبل إنشاء الحساب.',
  'patient.allProviders': 'كل مزودي الرعاية',
  'patient.voiceUnavailable': 'الإدخال الصوتي غير متاح على هذا الجهاز.',
  'patient.typeCareNeed': 'اكتب أو قل نوع الرعاية التي تحتاجها، ثم اضغط بحث.',
  'patient.providersLoading': 'قائمة المزودين ما زالت تتحمل - حاول بعد قليل.',
  'patient.goodMorning': 'صباح الخير',
  'patient.goodAfternoon': 'مساء الخير',
  'patient.goodEvening': 'مساء الخير',
  'patient.recommendedForYou': 'موصى به لك',
  'patient.typeOrSpeak':
      'اكتب أو تحدث عن حاجتك. لتوصية أدق، أضف سجلك الطبي من الملف الشخصي > السجلات الطبية.',
  'patient.recommended': 'موصى به: {provider}',
  'patient.find': 'بحث',
  'patient.stopVoice': 'إيقاف الإدخال الصوتي',
  'patient.speakNeed': 'تحدث عن الرعاية التي تحتاجها',
  'patient.signInEditProfile': 'سجل الدخول لتعديل ملفك الشخصي.',
  'patient.hiLoading': 'أهلاً...',
  'patient.hiName': 'أهلاً، {name}',
  'patient.bookNextVisit': 'احجز زيارتك القادمة',
  'patient.homeNursingCare': 'رعاية تمريض منزلية',
  'patient.trustedCare': 'رعاية موثوقة',
  'patient.book': 'حجز',
  'patient.navHome': 'الرئيسية',
  'patient.navCare': 'رعايتي',
  'patient.navChat': 'الدردشة',
  'patient.navProfile': 'الملف',
  'patient.listening': 'أستمع',
  'patient.listeningRequest': 'أستمع إلى طلبك',
  'patient.askAi': 'اسأل ذكاء CareLink',
  'patient.sayOrType': 'قل أو اكتب نوع الرعاية لترتيب المزودين.',
  'nurse.title': 'كيرلينك - الممرض',
  'nurse.dashboard': 'اللوحة',
  'nurse.requests': 'الطلبات',
  'nurse.reports': 'التقارير',
  'nurse.payments': 'المدفوعات',
  'nurse.settings': 'الإعدادات',
  'nurse.welcome': 'أهلاً، {name}',
  'nurse.matter': 'خدماتك الصحية تصنع فرقاً',
  'nurse.quickOverview': 'نظرة سريعة',
  'nurse.pendingRequests': 'طلبات قيد الانتظار',
  'nurse.todaysVisits': 'زيارات اليوم',
  'nurse.completed': 'مكتملة',
  'nurse.earnings': 'الأرباح',
  'nurse.quickActions': 'إجراءات سريعة',
  'nurse.profile': 'الملف المهني',
  'nurse.profileSubtitle': 'حدّث ملفك المهني',
  'nurse.serviceRequests': 'طلبات الخدمة',
  'nurse.serviceRequestsSubtitle': 'اقبل أو ارفض الطلبات الجديدة',
  'nurse.submitReport': 'إرسال تقرير',
  'nurse.submitReportSubtitle': 'وثّق الزيارات المكتملة',
  'nurse.paymentHistory': 'سجل المدفوعات',
  'nurse.paymentHistorySubtitle': 'راجع الأرباح والمدفوعات',
  'nurse.settingsSubtitle': 'إدارة الملف والتفضيلات',
};
